// ~30 "listicle" themes in the a.png card world. All in-image copy is English.
// Each theme -> cover + one slide per item + closing.
// Each item carries: name, tag (short category), a fuller 2-sentence desc, and
// two short takeaways (points), plus a motif from illustrations.js. Nodeflare
// shows up naturally as one pick among many in the MCP / hosting themes.

export const THEMES = [
  {
    id: 'ai-tools-cheating',
    eyebrow: 'AI Tools',
    title: '7 AI tools that feel like cheating',
    subtitle: 'The stack that quietly saves me hours every single week.',
    hook: 'sparkle',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more tools worth your time.' },
    items: [
      { name: 'ChatGPT', tag: 'AI Chat', motif: 'chat',
        desc: 'Your all-purpose thinking partner for drafts, code, and half-formed ideas. Ask it to plan, rewrite, or explain, and it keeps up in plain language.',
        points: ['Turns a blank page into a first draft in seconds', 'Great for brainstorming when you are stuck'] },
      { name: 'Perplexity', tag: 'AI Search', motif: 'search',
        desc: 'Answers real questions with citations attached, so you can check the source instead of trusting a guess. It reads the web so you do not have to.',
        points: ['Every claim links back to where it came from', 'Replaces ten open tabs with one clear answer'] },
      { name: 'Whisper', tag: 'Transcription', motif: 'mic',
        desc: 'Drop in hours of audio and get back clean, accurate text in a single command. It handles accents, jargon, and messy recordings with ease.',
        points: ['Runs offline on your own machine', 'Perfect for notes, interviews, and subtitles'] },
      { name: 'Midjourney', tag: 'AI Image', motif: 'image',
        desc: 'Turn one line of text into striking concept art, mockups, and moodboards. It is the fastest way to see an idea before you commit to it.',
        points: ['Studio-quality visuals with no design skills', 'Iterate on a look in minutes, not days'] },
      { name: 'Cursor', tag: 'AI Coding', motif: 'code',
        desc: 'An editor that writes, refactors, and explains code right beside you, with your whole project in context. It feels like pairing with a senior dev.',
        points: ['Edits across many files from one prompt', 'Catches bugs before you even run the code'] },
      { name: 'Raycast AI', tag: 'Launcher', motif: 'bolt',
        desc: 'Ask, translate, and summarize without ever leaving your keyboard. One hotkey puts an assistant on top of every app you already use.',
        points: ['No browser tab, no context switch', 'Automate repetitive steps with quick commands'] },
      { name: 'Nodeflare', tag: 'MCP Hosting', motif: 'plug',
        desc: 'Host any MCP server straight from a GitHub URL and give your AI real tools, with full access logs on every call. No forking, no infra to babysit.',
        points: ['Per-tool allow lists keep agents in check', 'Three servers free, with a clean audit trail'] },
    ],
  },
  {
    id: 'mcp-servers-start',
    eyebrow: 'MCP Servers',
    title: '6 MCP servers worth setting up first',
    subtitle: 'Give your AI real tools, not just conversation.',
    hook: 'plug',
    closing: { title: 'Start with\nthese', subtitle: 'One URL and your agent gets superpowers.' },
    items: [
      { name: 'Filesystem', tag: 'Files', motif: 'doc',
        desc: 'Lets the model read and edit local files inside a folder you choose. It is the simplest way to make an assistant actually useful on your machine.',
        points: ['Scope it to one directory for safety', 'Great for refactors and bulk edits'] },
      { name: 'GitHub', tag: 'Code', motif: 'code',
        desc: 'Open issues, review pull requests, and search code straight from chat. Your assistant can now work where your team already does.',
        points: ['Triage issues without leaving the thread', 'Summarize a PR in plain English'] },
      { name: 'Postgres', tag: 'Database', motif: 'database',
        desc: 'Ask questions in plain English and get real query results back. It turns your database into something anyone on the team can interrogate.',
        points: ['No more copy-pasting SQL around', 'Read-only mode keeps data safe'] },
      { name: 'Playwright', tag: 'Browser', motif: 'globe',
        desc: 'Drives a real browser so your agent can test flows and scrape pages. It clicks, types, and reads exactly like a human would.',
        points: ['Automate end-to-end checks', 'Pull data from sites without an API'] },
      { name: 'Nodeflare', tag: 'Hosting', motif: 'plug',
        desc: 'Deploys any stdio server as a hosted, audited endpoint from a URL. It is the fastest path from a GitHub repo to a live MCP tool.',
        points: ['Turns any repo into an SSE endpoint', 'Full logs on every single call'] },
      { name: 'Memory', tag: 'Context', motif: 'brain',
        desc: 'Gives the assistant durable notes that survive across sessions. It remembers your preferences so you stop repeating yourself.',
        points: ['Persistent context between chats', 'Teach it once, benefit forever'] },
    ],
  },
  {
    id: 'ai-writing',
    eyebrow: 'AI Writing',
    title: '6 AI writing tools that beat a blank page',
    subtitle: 'From first draft to final polish, a lot faster.',
    hook: 'pen',
    closing: { title: 'Write\nfaster', subtitle: 'Save this next time you stare at a cursor.' },
    items: [
      { name: 'Claude', tag: 'Long Form', motif: 'chat',
        desc: 'Produces long, careful drafts that keep your voice instead of flattening it. It is the one to reach for when the writing actually matters.',
        points: ['Holds a whole document in context', 'Rewrites without losing your tone'] },
      { name: 'Grammarly', tag: 'Editing', motif: 'doc',
        desc: 'Catches the mistakes you stopped seeing three hours ago. It quietly fixes grammar, clarity, and tone as you type anywhere.',
        points: ['Works across every app you write in', 'Explains why, so you learn'] },
      { name: 'Notion AI', tag: 'In-Doc', motif: 'pen',
        desc: 'Summarizes, expands, and rewrites right inside your notes. There is no copy-pasting between tools to break your flow.',
        points: ['Turn rough bullets into prose', 'Summarize a long page in one click'] },
      { name: 'Hemingway', tag: 'Clarity', motif: 'wand',
        desc: 'Highlights dense sentences until every line lands harder. It pushes you toward writing that people actually finish.',
        points: ['Flags passive voice and filler', 'Scores your readability instantly'] },
      { name: 'DeepL Write', tag: 'Rephrasing', motif: 'globe',
        desc: 'Rephrases text so it reads like a native speaker wrote it. It is the difference between correct and genuinely natural.',
        points: ['Multiple tones at a click', 'Excellent across languages'] },
      { name: 'Descript', tag: 'Audio Text', motif: 'mic',
        desc: 'Lets you edit audio and video by editing the transcript. Delete a word from the text and it vanishes from the recording.',
        points: ['Cut filler by deleting words', 'Turn talks into clean articles'] },
    ],
  },
  {
    id: 'ai-image',
    eyebrow: 'AI Image',
    title: '6 AI image tools designers actually use',
    subtitle: 'Mockups, art, and edits without opening Photoshop.',
    hook: 'image',
    closing: { title: 'Design\nfaster', subtitle: 'Save this for your next visual sprint.' },
    items: [
      { name: 'Midjourney', tag: 'Concept Art', motif: 'image',
        desc: 'The gold standard for striking, painterly concept art. It sets the mood for a project faster than any brief ever could.',
        points: ['Unmatched sense of style', 'Great for pitches and moodboards'] },
      { name: 'Flux', tag: 'Open Model', motif: 'sparkle',
        desc: 'Open-weight image generation with sharp text and fine detail. You can run it yourself and tune it to your own look.',
        points: ['Renders legible text at last', 'Self-hostable and hackable'] },
      { name: 'Ideogram', tag: 'Typography', motif: 'palette',
        desc: 'The model that finally gets typography and layout right. Posters, logos, and lockups come out usable, not garbled.',
        points: ['Clean, readable lettering', 'Strong at logos and posters'] },
      { name: 'Krea', tag: 'Realtime', motif: 'wand',
        desc: 'A real-time canvas that renders as you sketch and drag. It closes the gap between an idea and seeing it.',
        points: ['Instant feedback while you draw', 'Great for rapid exploration'] },
      { name: 'Photoroom', tag: 'Editing', motif: 'magnet',
        desc: 'Clean product cutouts and background swaps in seconds. It makes a phone photo look like a studio shot.',
        points: ['Perfect cutouts, no masking', 'Batch a whole catalog fast'] },
      { name: 'Recraft', tag: 'Brand Sets', motif: 'palette',
        desc: 'Generates vector and brand-consistent sets, not one-off images. It keeps a whole series looking like it belongs together.',
        points: ['Exports crisp vectors', 'Locks a consistent style'] },
    ],
  },
  {
    id: 'dev-cli',
    eyebrow: 'Terminal',
    title: '7 CLI tools that upgrade your terminal',
    subtitle: 'Modern replacements for commands you use every day.',
    hook: 'terminal',
    closing: { title: 'Level up\nyour shell', subtitle: 'Save this and install them tonight.' },
    items: [
      { name: 'ripgrep', tag: 'Search', motif: 'search',
        desc: 'Searches huge codebases in a blink while respecting gitignore. Once you use it, plain grep feels like it stopped for coffee.',
        points: ['Absurdly fast on big repos', 'Sensible defaults out of the box'] },
      { name: 'fzf', tag: 'Fuzzy Find', motif: 'bolt',
        desc: 'A fuzzy finder for files, history, branches, and processes. Pipe anything into it and pick with a few keystrokes.',
        points: ['Fuzzy-select from any list', 'Supercharges your shell history'] },
      { name: 'bat', tag: 'Viewer', motif: 'doc',
        desc: 'Like cat, but with syntax highlighting and line numbers. Reading files in the terminal finally looks good.',
        points: ['Syntax colors for everything', 'Git change markers built in'] },
      { name: 'eza', tag: 'Listing', motif: 'terminal',
        desc: 'A friendlier ls with icons, git status, and tree views. The same information, far easier to scan.',
        points: ['See git status inline', 'Tree view without a flag soup'] },
      { name: 'zoxide', tag: 'Navigation', motif: 'rocket',
        desc: 'Jump to any directory by a fragment of its name. It learns where you go and gets you there in two letters.',
        points: ['No more long cd chains', 'Learns your habits over time'] },
      { name: 'lazygit', tag: 'Git UI', motif: 'code',
        desc: 'A fast terminal UI that makes git finally make sense. Staging, rebasing, and stashing become a few keystrokes.',
        points: ['Interactive rebase without fear', 'See everything at a glance'] },
      { name: 'delta', tag: 'Diffs', motif: 'chart',
        desc: 'Turns git diffs into something you can actually read. Side-by-side, syntax-aware, and easy on the eyes.',
        points: ['Readable side-by-side diffs', 'Highlights moved lines'] },
    ],
  },
  {
    id: 'self-host',
    eyebrow: 'Self-Hosting',
    title: '6 tools to run your own cloud',
    subtitle: 'Own your data without babysitting servers.',
    hook: 'cloud',
    closing: { title: 'Own your\nstack', subtitle: 'Save this before your next subscription renews.' },
    items: [
      { name: 'Coolify', tag: 'PaaS', motif: 'rocket',
        desc: 'Deploys apps and databases with a Heroku-style interface you host. It is the easy button for your own server.',
        points: ['Push to deploy, on your box', 'Databases and backups included'] },
      { name: 'Nodeflare', tag: 'MCP Hosting', motif: 'plug',
        desc: 'Hosts MCP servers with auth and logs and no infra to run. You get a hosted endpoint from a URL in minutes.',
        points: ['No servers to maintain', 'Auth and audit logs built in'] },
      { name: 'Immich', tag: 'Photos', motif: 'image',
        desc: 'A private, self-hosted alternative to Google Photos. Your memories stay on hardware you actually control.',
        points: ['Automatic phone backup', 'Face and object search'] },
      { name: 'Paperless', tag: 'Documents', motif: 'doc',
        desc: 'Scans, indexes, and searches every document you own. It turns a shoebox of paper into a searchable archive.',
        points: ['Full-text search on scans', 'Auto-tags incoming files'] },
      { name: 'Vaultwarden', tag: 'Passwords', motif: 'shield',
        desc: 'Your own password manager, fully under your control. Compatible with Bitwarden apps but hosted by you.',
        points: ['Sync across all devices', 'Your secrets never leave home'] },
      { name: 'Uptime Kuma', tag: 'Monitoring', motif: 'chart',
        desc: 'Beautiful status pages and alerts for all your services. You will know something is down before your users do.',
        points: ['Alerts to any channel', 'Gorgeous status pages'] },
    ],
  },
  {
    id: 'ai-video',
    eyebrow: 'AI Video',
    title: '6 AI video tools for creators',
    subtitle: 'Shoot less, ship more, with a smaller team.',
    hook: 'video',
    closing: { title: 'Make\nvideo', subtitle: 'Save this for your next upload.' },
    items: [
      { name: 'Runway', tag: 'Generation', motif: 'video',
        desc: 'Generates and edits clips with text and reference frames. It is a whole VFX department that fits in a browser tab.',
        points: ['Text-to-video in minutes', 'Powerful in-browser editing'] },
      { name: 'CapCut', tag: 'Editing', motif: 'wand',
        desc: 'Fast edits, captions, and effects built for short form. It is why so many viral clips look the way they do.',
        points: ['Auto captions that sync', 'Trending templates ready to go'] },
      { name: 'HeyGen', tag: 'Avatars', motif: 'robot',
        desc: 'Turns a script into a talking avatar in any language. Record once and localize to the whole world.',
        points: ['Dozens of languages', 'No camera required'] },
      { name: 'Descript', tag: 'Transcript Edit', motif: 'mic',
        desc: 'Cut filler words by deleting them from the transcript. Editing video becomes as easy as editing a doc.',
        points: ['Remove ums in one click', 'Overdub fixes without reshooting'] },
      { name: 'Submagic', tag: 'Captions', motif: 'chat',
        desc: 'Auto captions that actually match your pacing and style. Animated, on-brand, and ready to post.',
        points: ['Styled captions in seconds', 'Emoji and keyword highlights'] },
      { name: 'ElevenLabs', tag: 'Voiceover', motif: 'mic',
        desc: 'Voiceovers so natural you forget they are synthetic. Clone a voice or pick one and start narrating.',
        points: ['Lifelike narration', 'Consistent across long videos'] },
    ],
  },
  {
    id: 'note-taking',
    eyebrow: 'Notes',
    title: '6 note apps that fit how you think',
    subtitle: 'Capture ideas before they slip away for good.',
    hook: 'pen',
    closing: { title: 'Think\nclearly', subtitle: 'Save this and pick one this week.' },
    items: [
      { name: 'Obsidian', tag: 'Second Brain', motif: 'brain',
        desc: 'Local markdown notes that link into a personal knowledge graph. Your thinking stays yours, in plain files forever.',
        points: ['Own your notes as files', 'Links reveal hidden connections'] },
      { name: 'Notion', tag: 'All-in-One', motif: 'doc',
        desc: 'Docs, databases, and wikis in one flexible canvas. It bends to fit almost any workflow you can imagine.',
        points: ['Databases meet documents', 'Templates for everything'] },
      { name: 'Apple Notes', tag: 'Quick Capture', motif: 'pen',
        desc: 'The fastest capture that is already on your phone. No setup, no friction, always one swipe away.',
        points: ['Instant, zero friction', 'Syncs across Apple devices'] },
      { name: 'Logseq', tag: 'Outliner', motif: 'calendar',
        desc: 'Outliner-first notes with daily journals built in. Ideal for people who think in bullets and backlinks.',
        points: ['Daily notes by default', 'Local-first and private'] },
      { name: 'Anytype', tag: 'Local-First', motif: 'shield',
        desc: 'Private, local-first, and fully yours to own. A Notion-like experience without the lock-in.',
        points: ['Encrypted and offline', 'No vendor holding your data'] },
      { name: 'Reflect', tag: 'Networked', motif: 'sparkle',
        desc: 'Networked notes with AI that connects the dots for you. It surfaces related thoughts as you write.',
        points: ['Backlinks made effortless', 'AI suggests connections'] },
    ],
  },
  {
    id: 'automation',
    eyebrow: 'Automation',
    title: '6 tools to automate the boring stuff',
    subtitle: 'Let software do the work you keep repeating.',
    hook: 'gear',
    closing: { title: 'Automate\nit', subtitle: 'Save this and reclaim an afternoon.' },
    items: [
      { name: 'n8n', tag: 'Open Source', motif: 'gear',
        desc: 'Open-source workflows you can self-host and extend freely. It connects your apps without monthly per-task fees.',
        points: ['Self-host with no limits', 'Custom code when you need it'] },
      { name: 'Zapier', tag: 'No-Code', motif: 'bolt',
        desc: 'Connects thousands of apps with zero code required. If two tools have an API, Zapier can bridge them.',
        points: ['Huge library of integrations', 'Build a flow in minutes'] },
      { name: 'Make', tag: 'Visual Logic', motif: 'chart',
        desc: 'Visual scenarios for complex, branching automations. When Zapier is too simple, Make handles the rest.',
        points: ['Branches, loops, and filters', 'See the whole flow at once'] },
      { name: 'Raycast', tag: 'Shortcuts', motif: 'rocket',
        desc: 'Scripts and shortcuts always a single keystroke away. It automates the little things you do a hundred times a day.',
        points: ['One hotkey for any action', 'A growing store of extensions'] },
      { name: 'Cron', tag: 'Scheduling', motif: 'calendar',
        desc: 'The humble scheduler that never forgets a task. Set it once and it runs quietly forever.',
        points: ['Rock-solid and everywhere', 'Perfect for recurring jobs'] },
      { name: 'Nodeflare', tag: 'Agent Tools', motif: 'plug',
        desc: 'Gives agents audited tools so automations stay safe. Every action is logged and every scope is explicit.',
        points: ['Least-privilege by default', 'A record of every call'] },
    ],
  },
  {
    id: 'research',
    eyebrow: 'Research',
    title: '6 tools for faster, deeper research',
    subtitle: 'Find the signal without drowning in tabs.',
    hook: 'search',
    closing: { title: 'Research\nsmarter', subtitle: 'Save this for your next deep dive.' },
    items: [
      { name: 'Perplexity', tag: 'Answers', motif: 'search',
        desc: 'Gives cited answers you can verify at a glance. It reads dozens of sources so you can trust the result.',
        points: ['Sources on every claim', 'Follow-up questions that build'] },
      { name: 'Elicit', tag: 'Papers', motif: 'doc',
        desc: 'Summarizes academic papers into plain, comparable findings. It turns a literature review into an afternoon.',
        points: ['Extracts key findings', 'Compare studies side by side'] },
      { name: 'Consensus', tag: 'Evidence', motif: 'chart',
        desc: 'Tells you what the studies actually agree on. Ask a yes-or-no question and see the weight of evidence.',
        points: ['Consensus at a glance', 'Grounded in real papers'] },
      { name: 'NotebookLM', tag: 'Your Sources', motif: 'brain',
        desc: 'Answers questions across your own PDFs and notes. It only speaks from the material you give it.',
        points: ['Grounded in your documents', 'Cites the exact passage'] },
      { name: 'Zotero', tag: 'References', motif: 'database',
        desc: 'Collects, organizes, and cites every reference you find. It is the quiet backbone of serious research.',
        points: ['One-click citation capture', 'Formats bibliographies for you'] },
      { name: 'Readwise', tag: 'Recall', motif: 'sparkle',
        desc: 'Resurfaces your highlights so you actually remember them. Spaced review turns reading into knowledge.',
        points: ['Daily highlight review', 'Syncs from every reader'] },
    ],
  },
  {
    id: 'coding-ai',
    eyebrow: 'AI Coding',
    title: '6 AI tools that make you a faster dev',
    subtitle: 'Ship features while the boilerplate writes itself.',
    hook: 'code',
    closing: { title: 'Ship\nfaster', subtitle: 'Save this and try one on your next task.' },
    items: [
      { name: 'Claude Code', tag: 'Agent', motif: 'terminal',
        desc: 'An agent that edits, runs, and tests your repo end to end. It does the multi-step grunt work while you steer.',
        points: ['Runs tests and fixes itself', 'Understands the whole project'] },
      { name: 'Cursor', tag: 'Editor', motif: 'code',
        desc: 'Multi-file edits with your entire codebase in context. It refactors across files without losing the thread.',
        points: ['Codebase-aware edits', 'Chat that knows your files'] },
      { name: 'Copilot', tag: 'Autocomplete', motif: 'sparkle',
        desc: 'Autocomplete that finishes the line you meant to write. It is the low-friction way to move a little faster all day.',
        points: ['Suggestions as you type', 'Learns your patterns'] },
      { name: 'Codeium', tag: 'Free Tier', motif: 'bolt',
        desc: 'A free, fast completion engine for nearly every editor. Strong suggestions without a subscription.',
        points: ['Free for individuals', 'Works in dozens of IDEs'] },
      { name: 'Aider', tag: 'Terminal Pair', motif: 'gear',
        desc: 'Pair-programs in the terminal with git-aware edits. Every change lands as a clean, reviewable commit.',
        points: ['Commits as it goes', 'Works with your existing repo'] },
      { name: 'Nodeflare', tag: 'MCP Tools', motif: 'plug',
        desc: 'Wires agents to real tools through hosted MCP servers. Your coding agent gains safe access to the outside world.',
        points: ['Real tools, real guardrails', 'Logs for every action'] },
    ],
  },
  {
    id: 'privacy',
    eyebrow: 'Privacy',
    title: '6 tools to take back your privacy',
    subtitle: 'Small swaps that stop the quiet data leaks.',
    hook: 'shield',
    closing: { title: 'Go\nprivate', subtitle: 'Save this and switch one thing today.' },
    items: [
      { name: 'Signal', tag: 'Messaging', motif: 'chat',
        desc: 'End-to-end encrypted messaging with nothing to sell. The gold standard, recommended by security experts everywhere.',
        points: ['Nobody reads your messages', 'Open source and audited'] },
      { name: 'Proton Mail', tag: 'Email', motif: 'mail',
        desc: 'Encrypted email that keeps your inbox genuinely yours. Even the provider cannot read your mail.',
        points: ['Zero-access encryption', 'Based in privacy-friendly Switzerland'] },
      { name: 'Bitwarden', tag: 'Passwords', motif: 'shield',
        desc: 'Strong, unique passwords without the memory tax. Open source, audited, and free for the essentials.',
        points: ['Unique password per site', 'Sync everywhere for free'] },
      { name: 'Mullvad', tag: 'VPN', motif: 'globe',
        desc: 'A strict no-logs VPN you can pay for anonymously. No email, no account, just a number.',
        points: ['No logs, no account', 'Flat, honest pricing'] },
      { name: 'DuckDuckGo', tag: 'Search', motif: 'search',
        desc: 'Search that does not build a profile of you. Good results without the surveillance tax.',
        points: ['No tracking, no bubble', 'Blocks hidden trackers too'] },
      { name: 'Tailscale', tag: 'Networking', motif: 'plug',
        desc: 'A private network between your own devices in minutes. Reach your machines without exposing anything publicly.',
        points: ['No open ports to attack', 'Works behind any firewall'] },
    ],
  },
  {
    id: 'design-tools',
    eyebrow: 'Design',
    title: '6 design tools for non-designers',
    subtitle: 'Make things look good without the degree.',
    hook: 'palette',
    closing: { title: 'Design it\nyourself', subtitle: 'Save this for your next project.' },
    items: [
      { name: 'Figma', tag: 'UI Design', motif: 'palette',
        desc: 'Design and prototype anything, together, in the browser. It became the industry standard for a reason.',
        points: ['Real-time collaboration', 'Prototype without code'] },
      { name: 'Canva', tag: 'Templates', motif: 'image',
        desc: 'Templates that turn a vague idea into a finished post. Drag, drop, and it already looks professional.',
        points: ['Thousands of templates', 'On-brand in a few clicks'] },
      { name: 'Coolors', tag: 'Color', motif: 'sparkle',
        desc: 'Generates palettes that actually work together. Hit the spacebar until a combination clicks.',
        points: ['Instant palette ideas', 'Export to any tool'] },
      { name: 'Fontshare', tag: 'Type', motif: 'doc',
        desc: 'Quality typefaces that are free for commercial use. Good type instantly lifts anything you make.',
        points: ['Free for commercial work', 'Curated, professional fonts'] },
      { name: 'Phosphor', tag: 'Icons', motif: 'wand',
        desc: 'A clean, consistent icon set for every screen you build. One coherent family instead of a mismatched pile.',
        points: ['Thousands of icons', 'Multiple weights included'] },
      { name: 'Blush', tag: 'Illustration', motif: 'pen',
        desc: 'Customizable illustrations you can recolor and drop in. Add personality without hiring an illustrator.',
        points: ['Mix and match styles', 'Recolor to match your brand'] },
    ],
  },
  {
    id: 'productivity',
    eyebrow: 'Productivity',
    title: '7 tools to get more done, calmly',
    subtitle: 'Less busywork, more of the work that matters.',
    hook: 'bolt',
    closing: { title: 'Do less,\nbetter', subtitle: 'Save this and cut one distraction today.' },
    items: [
      { name: 'Todoist', tag: 'Tasks', motif: 'doc',
        desc: 'Captures tasks fast and reminds you at the right time. Trust the system and get it out of your head.',
        points: ['Natural-language due dates', 'Works on every device'] },
      { name: 'Cal.com', tag: 'Scheduling', motif: 'calendar',
        desc: 'Share one link and end the back-and-forth of scheduling. People just pick a slot that works.',
        points: ['No more email tennis', 'Open source and self-hostable'] },
      { name: 'Raycast', tag: 'Launcher', motif: 'rocket',
        desc: 'Launch, search, and automate from a single hotkey. It becomes the command center for your whole Mac.',
        points: ['Everything a keystroke away', 'Extensions for every app'] },
      { name: 'Cron', tag: 'Calendar', motif: 'calendar',
        desc: 'A fast, keyboard-first calendar that respects your focus. Planning your day stops feeling like a chore.',
        points: ['Blazing keyboard shortcuts', 'Time-zone friendly'] },
      { name: 'Superhuman', tag: 'Email', motif: 'mail',
        desc: 'Inbox zero at a speed that feels almost unfair. Every action is tuned to shave off seconds.',
        points: ['Fly through email', 'Snooze and remind built in'] },
      { name: 'Freedom', tag: 'Focus', motif: 'shield',
        desc: 'Blocks the sites and apps that steal your afternoons. Schedule sessions and let it hold the line.',
        points: ['Block across all devices', 'Recurring focus sessions'] },
      { name: 'Toggl', tag: 'Time', motif: 'chart',
        desc: 'Shows you where your hours actually go. Awareness alone changes how you spend them.',
        points: ['One-tap time tracking', 'Reports that reveal leaks'] },
    ],
  },
  {
    id: 'data-tools',
    eyebrow: 'Data',
    title: '6 tools for working with data',
    subtitle: 'From raw rows to real answers, faster.',
    hook: 'database',
    closing: { title: 'Query\nanything', subtitle: 'Save this for your next dataset.' },
    items: [
      { name: 'DuckDB', tag: 'Analytics', motif: 'database',
        desc: 'Runs fast analytics on huge files right on your laptop. No cluster, no setup, just point it at your data.',
        points: ['Query gigabytes locally', 'Reads CSV and Parquet directly'] },
      { name: 'Metabase', tag: 'Dashboards', motif: 'chart',
        desc: 'Dashboards your whole team can build and read. It puts answers in the hands of non-analysts.',
        points: ['Ask questions without SQL', 'Share charts in seconds'] },
      { name: 'Polars', tag: 'DataFrames', motif: 'bolt',
        desc: 'DataFrames that scream through millions of rows. A modern, faster take on the classic pandas workflow.',
        points: ['Multi-core by default', 'Lazy queries that optimize'] },
      { name: 'Observable', tag: 'Notebooks', motif: 'sparkle',
        desc: 'Notebooks that turn data into live, interactive visuals. Explore and explain in the same place.',
        points: ['Reactive, live charts', 'Share as a web page'] },
      { name: 'dbt', tag: 'Transform', motif: 'gear',
        desc: 'Version-controlled transforms your analysts can trust. It brings software discipline to your data pipeline.',
        points: ['Tested, documented models', 'Git workflow for data'] },
      { name: 'Nodeflare', tag: 'MCP Access', motif: 'plug',
        desc: 'Lets an agent query your database through a safe MCP tool. Natural-language questions, with guardrails on.',
        points: ['Read-only scopes', 'Every query is logged'] },
    ],
  },
  {
    id: 'ai-audio',
    eyebrow: 'AI Audio',
    title: '6 AI audio tools that sound pro',
    subtitle: 'Voice, music, and cleanup without a studio.',
    hook: 'mic',
    closing: { title: 'Sound\ngreat', subtitle: 'Save this for your next recording.' },
    items: [
      { name: 'ElevenLabs', tag: 'Voice', motif: 'mic',
        desc: 'Lifelike voices and dubbing in dozens of languages. Clone a voice or pick one and start narrating instantly.',
        points: ['Human-quality narration', 'Dub content into any language'] },
      { name: 'Suno', tag: 'Music', motif: 'sparkle',
        desc: 'Full songs from a prompt, lyrics and vocals included. Background tracks and jingles in a minute.',
        points: ['Original music on demand', 'Royalty-free for your videos'] },
      { name: 'Adobe Podcast', tag: 'Cleanup', motif: 'wand',
        desc: 'Makes shaky recordings sound studio-clean. It removes echo and noise like magic.',
        points: ['Studio sound from a laptop mic', 'Free to use in the browser'] },
      { name: 'Whisper', tag: 'Transcribe', motif: 'chat',
        desc: 'Accurate transcription for any audio you have. The open model that powers half the tools on this list.',
        points: ['Handles noisy audio', 'Runs locally and free'] },
      { name: 'Krisp', tag: 'Noise', motif: 'shield',
        desc: 'Removes background noise from any call in real time. Dogs, keyboards, and cafes just disappear.',
        points: ['Works in any meeting app', 'Two-way noise removal'] },
      { name: 'Audacity', tag: 'Editor', motif: 'chart',
        desc: 'The free, powerful editor that still does it all. Decades of features without a subscription.',
        points: ['Free and open source', 'Deep editing control'] },
    ],
  },
  {
    id: 'marketing',
    eyebrow: 'Marketing',
    title: '7 tools to grow without a big budget',
    subtitle: 'Do the work of a team of five, solo.',
    hook: 'rocket',
    closing: { title: 'Grow\nsmarter', subtitle: 'Save this and pick your next lever.' },
    items: [
      { name: 'Buffer', tag: 'Scheduling', motif: 'calendar',
        desc: 'Schedule a whole week of posts in one sitting. Stay consistent without living inside every app.',
        points: ['Queue posts everywhere', 'Simple analytics included'] },
      { name: 'Beehiiv', tag: 'Newsletter', motif: 'mail',
        desc: 'Grow and monetize a newsletter people actually open. Built by the team behind a giant one.',
        points: ['Referral growth built in', 'Monetize from day one'] },
      { name: 'Plausible', tag: 'Analytics', motif: 'chart',
        desc: 'Simple, private analytics with no cookie banner needed. All the numbers that matter, none of the creep.',
        points: ['Lightweight and private', 'One clear dashboard'] },
      { name: 'Ahrefs', tag: 'SEO', motif: 'search',
        desc: 'Finds the keywords your audience already searches for. Then shows you exactly how to rank for them.',
        points: ['Spy on what works', 'Find low-competition wins'] },
      { name: 'Opus Clip', tag: 'Repurpose', motif: 'video',
        desc: 'Turns one long video into ten short, punchy clips. It finds the best moments so you do not have to.',
        points: ['Auto-picks viral moments', 'Captions and reframing done'] },
      { name: 'Canva', tag: 'Graphics', motif: 'palette',
        desc: 'On-brand graphics without a designer on call. Templates make every post look intentional.',
        points: ['Brand kit keeps it consistent', 'Resize for every platform'] },
      { name: 'Typeform', tag: 'Forms', motif: 'doc',
        desc: 'Surveys and forms that people actually finish. One question at a time keeps them engaged.',
        points: ['Higher completion rates', 'Logic jumps built in'] },
    ],
  },
  {
    id: 'learning',
    eyebrow: 'Learning',
    title: '6 tools to learn anything faster',
    subtitle: 'Turn curiosity into skill that actually sticks.',
    hook: 'brain',
    closing: { title: 'Keep\nlearning', subtitle: 'Save this and start one today.' },
    items: [
      { name: 'Anki', tag: 'Flashcards', motif: 'calendar',
        desc: 'Spaced repetition that beats forgetting at its own game. It shows you a card right before you would lose it.',
        points: ['Remember far more, longer', 'Decks for almost any subject'] },
      { name: 'NotebookLM', tag: 'Study Aid', motif: 'doc',
        desc: 'Turns any material into a study guide and Q&A. Upload your sources and quiz yourself on them.',
        points: ['Instant study guides', 'Answers grounded in your notes'] },
      { name: 'Brilliant', tag: 'Interactive', motif: 'chart',
        desc: 'Teaches math and CS by doing, not by watching. Short, hands-on lessons that build real intuition.',
        points: ['Learn by solving', 'Bite-sized daily lessons'] },
      { name: 'YouTube', tag: 'Lectures', motif: 'video',
        desc: 'The best free lectures ever made, if you curate well. Nearly any skill has a great teacher on it.',
        points: ['World-class teachers, free', 'Playlists build a curriculum'] },
      { name: 'Excalidraw', tag: 'Sketching', motif: 'pen',
        desc: 'Sketch ideas until they finally click into place. Drawing a concept is how you truly learn it.',
        points: ['Think visually, fast', 'Share diagrams instantly'] },
      { name: 'Readwise', tag: 'Retention', motif: 'sparkle',
        desc: 'Reviews your highlights before they fade away. It turns passive reading into lasting knowledge.',
        points: ['Resurface what you read', 'Syncs from books and articles'] },
    ],
  },
  {
    id: 'browser-ext',
    eyebrow: 'Browser',
    title: '6 browser extensions worth installing',
    subtitle: 'Tiny add-ons, an outsized daily payoff.',
    hook: 'globe',
    closing: { title: 'Upgrade\nyour tabs', subtitle: 'Save this and clean up your browser.' },
    items: [
      { name: 'uBlock Origin', tag: 'Ad Block', motif: 'shield',
        desc: 'The ad blocker that is light and genuinely works. It makes the web faster and far less hostile.',
        points: ['Blocks ads and trackers', 'Barely uses any memory'] },
      { name: 'Bitwarden', tag: 'Passwords', motif: 'shield',
        desc: 'Autofills strong passwords everywhere you log in. One extension retires your reused passwords for good.',
        points: ['Fill logins in one click', 'Generate strong passwords'] },
      { name: 'Vimium', tag: 'Keyboard', motif: 'bolt',
        desc: 'Browse the entire web from your keyboard. Follow links and scroll without touching the mouse.',
        points: ['Click links by keyboard', 'Fly between tabs'] },
      { name: 'Reader', tag: 'Reading', motif: 'doc',
        desc: 'Strips the clutter so you can just read the article. Pop-ups and sidebars simply vanish.',
        points: ['Clean, distraction-free view', 'Adjustable fonts and width'] },
      { name: 'Raindrop', tag: 'Bookmarks', motif: 'magnet',
        desc: 'Bookmarks you will actually find again later. Visual, searchable, and neatly organized.',
        points: ['Save anything visually', 'Full-text search your saves'] },
      { name: 'JSON Viewer', tag: 'Dev', motif: 'code',
        desc: 'Pretty-prints API responses right in the browser tab. Raw JSON becomes a foldable, readable tree.',
        points: ['Collapsible JSON tree', 'Syntax highlighting built in'] },
    ],
  },
  {
    id: 'open-source-ai',
    eyebrow: 'Open Source',
    title: '6 open-source AI tools to self-host',
    subtitle: 'Run capable models on your own hardware.',
    hook: 'cloud',
    closing: { title: 'Run it\nlocally', subtitle: 'Save this for your home lab.' },
    items: [
      { name: 'Ollama', tag: 'Local Models', motif: 'terminal',
        desc: 'Runs open models locally with a single command. It is the easiest on-ramp to private, offline AI.',
        points: ['One command to start', 'No data leaves your machine'] },
      { name: 'Open WebUI', tag: 'Chat UI', motif: 'chat',
        desc: 'A polished chat interface for your local models. It feels like a hosted product, but it is all yours.',
        points: ['Clean, familiar interface', 'Multi-user and self-hosted'] },
      { name: 'LM Studio', tag: 'Model Hub', motif: 'search',
        desc: 'Discover, download, and test models with a friendly GUI. Perfect for trying models before you commit.',
        points: ['Browse and grab models', 'Test with a built-in chat'] },
      { name: 'Whisper.cpp', tag: 'Speech', motif: 'mic',
        desc: 'Fast, offline transcription on modest hardware. It runs great even without a big GPU.',
        points: ['CPU-friendly and fast', 'Fully private transcription'] },
      { name: 'ComfyUI', tag: 'Image Gen', motif: 'image',
        desc: 'Node-based image generation you fully control. Build a pipeline exactly the way you want it.',
        points: ['Total control of the workflow', 'A huge library of nodes'] },
      { name: 'Nodeflare', tag: 'MCP Hosting', motif: 'plug',
        desc: 'Exposes your local tools to agents, safely, over MCP. Your home lab becomes an agent toolbox.',
        points: ['Share local tools securely', 'Auth and logs included'] },
    ],
  },
  {
    id: 'api-tools',
    eyebrow: 'APIs',
    title: '6 tools every API developer needs',
    subtitle: 'Build, test, and ship integrations with less pain.',
    hook: 'plug',
    closing: { title: 'Build\nAPIs', subtitle: 'Save this for your next integration.' },
    items: [
      { name: 'Bruno', tag: 'API Client', motif: 'bolt',
        desc: 'A fast, git-friendly API client that stays local. Your request collections live in the repo, not a cloud.',
        points: ['Collections as plain files', 'No account required'] },
      { name: 'Hoppscotch', tag: 'Testing', motif: 'globe',
        desc: 'Test requests in the browser with nothing to install. Open a tab and you are already working.',
        points: ['Zero-install and free', 'Open source and fast'] },
      { name: 'ngrok', tag: 'Tunneling', motif: 'plug',
        desc: 'Exposes localhost to the internet in one command. Perfect for webhooks and quick demos.',
        points: ['Public URL in seconds', 'Inspect traffic as it flows'] },
      { name: 'Mockoon', tag: 'Mocking', motif: 'gear',
        desc: 'Spins up realistic mock APIs in seconds. Build the frontend before the backend exists.',
        points: ['Fake an API instantly', 'Test edge cases on demand'] },
      { name: 'HTTPie', tag: 'CLI', motif: 'terminal',
        desc: 'Human-friendly requests straight from your terminal. Sensible syntax and colorized, readable output.',
        points: ['Readable command syntax', 'Pretty JSON by default'] },
      { name: 'Nodeflare', tag: 'MCP Bridge', motif: 'robot',
        desc: 'Turns any API into an MCP tool your agent can call. Give models safe, logged access to real services.',
        points: ['Any API becomes agent-ready', 'Scopes and logs on every call'] },
    ],
  },
  {
    id: 'focus',
    eyebrow: 'Focus',
    title: '6 tools to protect your attention',
    subtitle: 'Guard the deep work your best ideas need.',
    hook: 'shield',
    closing: { title: 'Protect\nfocus', subtitle: 'Save this and block one distraction.' },
    items: [
      { name: 'Freedom', tag: 'Blocker', motif: 'shield',
        desc: 'Schedules blocks that lock out the noise for you. Set it and it removes the temptation entirely.',
        points: ['Block across all devices', 'Recurring focus sessions'] },
      { name: 'Forest', tag: 'Gamified', motif: 'sparkle',
        desc: 'Grow a virtual tree by leaving your phone alone. A tiny game that makes focus feel rewarding.',
        points: ['Stay off your phone', 'Build a forest over time'] },
      { name: 'Brain.fm', tag: 'Sound', motif: 'mic',
        desc: 'Music engineered to keep you in a state of flow. Not playlists, but functional audio for focus.',
        points: ['Science-backed focus music', 'Modes for work and rest'] },
      { name: 'Cold Turkey', tag: 'Hard Block', motif: 'shield',
        desc: 'The blocker you truly cannot argue your way past. When willpower fails, it holds the line.',
        points: ['Impossible to bypass', 'Blocks apps and sites'] },
      { name: 'Sunsama', tag: 'Planning', motif: 'calendar',
        desc: 'Plans a realistic day, one intention at a time. It stops you overloading your to-do list.',
        points: ['A calm daily planning ritual', 'Pull tasks from every tool'] },
      { name: 'Reclaim', tag: 'Calendar AI', motif: 'gear',
        desc: 'Defends focus time on your calendar automatically. It fits tasks and breaks around your meetings.',
        points: ['Auto-schedules focus blocks', 'Protects time from meetings'] },
    ],
  },
  {
    id: 'devops',
    eyebrow: 'DevOps',
    title: '6 tools that make DevOps less painful',
    subtitle: 'Ship and observe without the 2am pages.',
    hook: 'gear',
    closing: { title: 'Ship with\nconfidence', subtitle: 'Save this for your next deploy.' },
    items: [
      { name: 'Docker', tag: 'Containers', motif: 'database',
        desc: 'Package an app once and run it the same everywhere. It ended a thousand it-works-on-my-machine arguments.',
        points: ['Consistent environments', 'Ships from laptop to prod'] },
      { name: 'Terraform', tag: 'Infra as Code', motif: 'doc',
        desc: 'Describes your infrastructure as code you can review. Changes get planned, approved, and versioned.',
        points: ['Review infra like code', 'Reproducible environments'] },
      { name: 'k9s', tag: 'Kubernetes', motif: 'terminal',
        desc: 'A fast terminal UI for taming Kubernetes clusters. It makes a scary system feel navigable.',
        points: ['See pods and logs live', 'Act without long commands'] },
      { name: 'Grafana', tag: 'Dashboards', motif: 'chart',
        desc: 'Dashboards that show trouble before your users feel it. All your metrics in one clear place.',
        points: ['Alerts on the metrics that matter', 'Connects to any data source'] },
      { name: 'Sentry', tag: 'Errors', motif: 'search',
        desc: 'Catches and traces errors down to the exact line. You learn about bugs before the tweets do.',
        points: ['Stack traces with context', 'Groups noise into real issues'] },
      { name: 'Caddy', tag: 'Web Server', motif: 'shield',
        desc: 'A web server with automatic HTTPS built right in. It handles certificates so you never think about them.',
        points: ['HTTPS with zero config', 'A tiny, readable config file'] },
    ],
  },
  {
    id: 'ai-agents',
    eyebrow: 'AI Agents',
    title: '6 tools for building AI agents',
    subtitle: 'Give models tools, memory, and a real job to do.',
    hook: 'robot',
    closing: { title: 'Build an\nagent', subtitle: 'Save this before your next prototype.' },
    items: [
      { name: 'MCP', tag: 'Standard', motif: 'plug',
        desc: 'The open standard for connecting models to tools and data. Build a tool once and every client can use it.',
        points: ['One protocol, many clients', 'A fast-growing ecosystem'] },
      { name: 'LangGraph', tag: 'Orchestration', motif: 'chart',
        desc: 'Models your agent flows as graphs you can reason about. Loops, branches, and retries become explicit.',
        points: ['Control complex flows', 'Inspect and debug each step'] },
      { name: 'Nodeflare', tag: 'Tool Hosting', motif: 'shield',
        desc: 'Hosts and audits the tools your agent depends on. It keeps powerful tools safe and observable.',
        points: ['Scoped, logged tool access', 'Deploy tools from a URL'] },
      { name: 'Pydantic AI', tag: 'Typed Output', motif: 'doc',
        desc: 'Typed, validated outputs you can actually trust. It turns fuzzy model text into reliable data.',
        points: ['Validate every response', 'Fewer runtime surprises'] },
      { name: 'Temporal', tag: 'Durability', motif: 'gear',
        desc: 'Durable workflows that survive crashes and retries. Long-running agents finally become reliable.',
        points: ['Resumes exactly where it stopped', 'Built-in retries and timeouts'] },
      { name: 'Chroma', tag: 'Memory', motif: 'database',
        desc: 'A vector store for agent memory and retrieval. It is how your agent recalls the right context.',
        points: ['Semantic search over memory', 'Simple to run locally'] },
    ],
  },
  {
    id: 'writing-longform',
    eyebrow: 'Creators',
    title: '6 tools for publishing online',
    subtitle: 'Own your words and reach real readers.',
    hook: 'pen',
    closing: { title: 'Start\npublishing', subtitle: 'Save this and post something this week.' },
    items: [
      { name: 'Ghost', tag: 'Publishing', motif: 'doc',
        desc: 'A clean, ownable home for your writing and members. It is a real business platform, not just a blog.',
        points: ['Own your audience and data', 'Memberships and paid tiers'] },
      { name: 'Substack', tag: 'Newsletter', motif: 'mail',
        desc: 'Newsletters with a built-in audience to discover you. The easiest way to start writing to real readers.',
        points: ['Discovery network built in', 'Free to start, easy to run'] },
      { name: 'Bear', tag: 'Drafting', motif: 'pen',
        desc: 'A calm, beautiful place to draft your ideas. Nothing to distract you from the words.',
        points: ['Focused, elegant editor', 'Markdown that just works'] },
      { name: 'Typefully', tag: 'Threads', motif: 'calendar',
        desc: 'Write and schedule threads that people actually read. It shapes your ideas for the timeline.',
        points: ['Draft and schedule threads', 'Analytics on what lands'] },
      { name: 'Unsplash', tag: 'Photos', motif: 'image',
        desc: 'Free, high-quality photos for every post you write. Good imagery instantly lifts your work.',
        points: ['Free for commercial use', 'Millions of quality photos'] },
      { name: 'Fathom', tag: 'Analytics', motif: 'chart',
        desc: 'Shows what readers love, privately and simply. Understand your audience without spying on them.',
        points: ['Privacy-first analytics', 'One simple dashboard'] },
    ],
  },
  {
    id: 'money-tools',
    eyebrow: 'Finance',
    title: '6 tools to run your money better',
    subtitle: 'See it clearly, then make it work for you.',
    hook: 'chart',
    closing: { title: 'Own your\nnumbers', subtitle: 'Save this and check in this weekend.' },
    items: [
      { name: 'Actual', tag: 'Budgeting', motif: 'shield',
        desc: 'Private, local-first budgeting you fully control. Envelope budgeting without handing over your bank login.',
        points: ['Your data stays with you', 'Open source and free'] },
      { name: 'Wise', tag: 'Transfers', motif: 'globe',
        desc: 'Sends money across borders at the real exchange rate. No hidden markup buried in the fees.',
        points: ['Transparent, low fees', 'Multi-currency account'] },
      { name: 'Ramp', tag: 'Expenses', motif: 'chart',
        desc: 'Corporate cards that track spend automatically. Expense reports basically write themselves.',
        points: ['Automatic receipt matching', 'Real-time spend controls'] },
      { name: 'Stripe', tag: 'Payments', motif: 'bolt',
        desc: 'Accept payments online with a few lines of code. It is the backbone of countless internet businesses.',
        points: ['Start charging in a day', 'Handles the hard compliance'] },
      { name: 'Beancount', tag: 'Plain Text', motif: 'doc',
        desc: 'Plain-text, double-entry books for the meticulous. Your finances live in files you can grep.',
        points: ['Auditable, forever', 'Powerful reports from text'] },
      { name: 'Ledger', tag: 'CLI', motif: 'database',
        desc: 'Query your finances like a database from the CLI. Slice your money any way you can imagine.',
        points: ['Command-line power', 'No lock-in, ever'] },
    ],
  },
  {
    id: 'team-tools',
    eyebrow: 'Teamwork',
    title: '6 tools for small teams that ship',
    subtitle: 'Coordinate without drowning in meetings.',
    hook: 'chat',
    closing: { title: 'Ship as\na team', subtitle: 'Save this for your next sprint.' },
    items: [
      { name: 'Linear', tag: 'Issues', motif: 'bolt',
        desc: 'Issue tracking so fast it stays out of your way. It is the tool teams rave about and never leave.',
        points: ['Keyboard-first and quick', 'Opinionated in the right ways'] },
      { name: 'Slack', tag: 'Chat', motif: 'chat',
        desc: 'Async chat that keeps context in one searchable place. Decisions stop getting lost in inboxes.',
        points: ['Channels keep it organized', 'Integrates with everything'] },
      { name: 'Loom', tag: 'Video', motif: 'video',
        desc: 'Record a quick video instead of booking another meeting. Show, do not schedule.',
        points: ['Replace status meetings', 'Async updates anyone can watch'] },
      { name: 'Excalidraw', tag: 'Whiteboard', motif: 'pen',
        desc: 'Whiteboard an idea together in seconds. The hand-drawn look keeps it low-stakes and fast.',
        points: ['Diagram together live', 'No account needed to start'] },
      { name: 'Height', tag: 'Projects', motif: 'gear',
        desc: 'Project management an AI can help you run. It automates the busywork of keeping things tidy.',
        points: ['Autopilot for grunt work', 'Flexible views per team'] },
      { name: 'Cal.com', tag: 'Scheduling', motif: 'calendar',
        desc: 'Book time without the email tennis. Share a link and let people self-serve.',
        points: ['Self-hostable', 'Round-robin for teams'] },
    ],
  },
  {
    id: 'security-tools',
    eyebrow: 'Security',
    title: '6 security tools everyone should use',
    subtitle: 'Basic hygiene that stops most attacks cold.',
    hook: 'shield',
    closing: { title: 'Stay\nsecure', subtitle: 'Save this and lock down one thing.' },
    items: [
      { name: '1Password', tag: 'Passwords', motif: 'shield',
        desc: 'Unique passwords and passkeys with almost no effort. The single biggest upgrade to your security.',
        points: ['A strong password per site', 'Passkeys and 2FA built in'] },
      { name: 'Authy', tag: '2FA', motif: 'bolt',
        desc: 'Two-factor codes that survive a lost or broken phone. Your second factor, safely backed up.',
        points: ['Encrypted cloud backup', 'Multi-device sync'] },
      { name: 'Have I Been Pwned', tag: 'Breaches', motif: 'search',
        desc: 'Tells you if your accounts are in a known breach. Free, trusted, and genuinely useful.',
        points: ['Check any email in seconds', 'Get alerts on new breaches'] },
      { name: 'Tailscale', tag: 'Access', motif: 'plug',
        desc: 'Reach your devices without opening any ports. A private mesh network that just works.',
        points: ['No exposed services', 'Access control per device'] },
      { name: 'age', tag: 'Encryption', motif: 'terminal',
        desc: 'Simple, modern file encryption from the command line. Encrypting a file is finally painless.',
        points: ['One small, auditable tool', 'Great for backups and secrets'] },
      { name: 'Nodeflare', tag: 'MCP Safety', motif: 'doc',
        desc: 'Per-tool allow lists and full logs for your MCP servers. It keeps AI tools from becoming a blind spot.',
        points: ['Allow or deny each method', 'A complete audit trail'] },
    ],
  },
  {
    id: 'startup-stack',
    eyebrow: 'Startups',
    title: '7 tools to launch a startup this weekend',
    subtitle: 'From idea to live product, lean and fast.',
    hook: 'rocket',
    closing: { title: 'Just\nlaunch', subtitle: 'Save this and start building tonight.' },
    items: [
      { name: 'Next.js', tag: 'Framework', motif: 'code',
        desc: 'A batteries-included framework for building for the web. It handles the plumbing so you build features.',
        points: ['Full-stack in one codebase', 'Huge ecosystem and docs'] },
      { name: 'Supabase', tag: 'Backend', motif: 'database',
        desc: 'Auth, database, and storage set up in minutes. A Postgres backend without the DevOps.',
        points: ['Real database, not a toy', 'Auth and APIs out of the box'] },
      { name: 'Vercel', tag: 'Hosting', motif: 'rocket',
        desc: 'Push to git and your app is instantly live. Deploys, previews, and scaling handled for you.',
        points: ['Zero-config deploys', 'Preview every pull request'] },
      { name: 'Stripe', tag: 'Payments', motif: 'bolt',
        desc: 'Start charging customers the very same day. The fastest path from product to revenue.',
        points: ['Revenue in hours, not weeks', 'Subscriptions made simple'] },
      { name: 'Resend', tag: 'Email', motif: 'mail',
        desc: 'Send transactional email that developers enjoy using. A clean API for the emails your app must send.',
        points: ['Developer-first email API', 'Great deliverability'] },
      { name: 'Nodeflare', tag: 'AI Tools', motif: 'plug',
        desc: 'Ship AI features on hosted MCP tools instead of glue code. Add real capabilities without building infra.',
        points: ['AI features without the plumbing', 'Safe, logged tool access'] },
      { name: 'Plausible', tag: 'Analytics', motif: 'chart',
        desc: 'Tells you if anyone is actually using it yet. Simple, private numbers you can act on.',
        points: ['Know your real traction', 'No cookie banner needed'] },
    ],
  },
  {
    id: 'chrome-ai-daily',
    eyebrow: 'AI Assistants',
    title: '6 AI assistants for your everyday tasks',
    subtitle: 'A helper for whatever you are stuck on right now.',
    hook: 'robot',
    closing: { title: 'Pick your\nhelper', subtitle: 'Save this and try one this week.' },
    items: [
      { name: 'Claude', tag: 'Reasoning', motif: 'chat',
        desc: 'Thoughtful help for writing, code, and hard questions. It thinks carefully instead of rushing to an answer.',
        points: ['Strong at nuanced tasks', 'Keeps your voice in writing'] },
      { name: 'ChatGPT', tag: 'All-Rounder', motif: 'robot',
        desc: 'The versatile everyday assistant for quick tasks. Whatever you throw at it, it makes a solid attempt.',
        points: ['Fast and flexible', 'A huge feature set'] },
      { name: 'Gemini', tag: 'Google-Tied', motif: 'sparkle',
        desc: 'Deeply tied into your docs, mail, and search. It shines when your life already lives in Google.',
        points: ['Works inside Workspace', 'Great at pulling from search'] },
      { name: 'Perplexity', tag: 'Sourced', motif: 'search',
        desc: 'The one to use when you need an answer with sources. It shows its work so you can verify.',
        points: ['Cited, checkable answers', 'Reads the live web'] },
      { name: 'Copilot', tag: 'Integrated', motif: 'bolt',
        desc: 'AI woven right into the tools you already use. Help appears where the work is happening.',
        points: ['Assist inside your apps', 'Low-friction everyday help'] },
      { name: 'Nodeflare', tag: 'Real Tools', motif: 'plug',
        desc: 'Gives any of them real tools through hosted MCP servers. Turn a chatbot into something that can act.',
        points: ['Add real-world actions', 'Safe, logged, and scoped'] },
    ],
  },
];

export function getTheme(id) {
  return THEMES.find((t) => t.id === id) || null;
}

export function listThemes() {
  return THEMES.map((t) => ({ id: t.id, title: t.title, items: t.items.length }));
}
