// ~30 broad, high-appeal "useful tools / free sites" listicle themes.
// All in-image copy is English. Each theme -> cover + one slide per item + closing.
// Item = { name, tag, desc (~2 sentences), points: [p1, p2], motif }.
// Nodeflare appears as ONE natural pick in the AI/builder-leaning themes only
// (it is an MCP HOSTING platform, not an MCP server) — described as "host any MCP
// server from a URL and give your AI real tools, 3 free". The broad "free sites"
// themes don't force it; nodeflare.tech stays as the footer brand throughout.
//
// The item count MUST match the number in each title ("7..." -> 7 items).

// Reusable Nodeflare pick (small variations by context via the `nf` helper).
function nf(tag, desc, p1, p2) {
  return { name: 'Nodeflare', tag, desc, points: [p1, p2], motif: 'plug' };
}
const NF = {
  cheating: nf('AI Infra',
    'Host any MCP server straight from a GitHub URL and give your AI real tools, with full access logs on every call. No forking, no infra to babysit.',
    'Per-tool allow lists keep agents in check', 'Three servers free, with a clean audit trail'),
  daily: nf('AI Tools',
    'Turns a chatbot into something that can actually do things — files, APIs, databases — through hosted MCP tools. One URL and your assistant gains real powers.',
    'Real actions, not just chat', 'Three servers free'),
  free: nf('Free Tier',
    'Host MCP servers from a URL and hand your AI safe, logged tools. Three servers are free with the full feature set, so you can start today.',
    'No card, three servers free', 'Auth and audit logs included'),
  power: nf('Agent Tools',
    'Give your AI real-world powers: read files, hit APIs, query databases — all through hosted MCP tools with per-method allow/deny and complete logs.',
    'Scoped access, full audit trail', 'Deploy a tool from a URL in minutes'),
  build: nf('AI Infra',
    'Ship AI features without wiring up servers: host any MCP tool from a URL and let your app call it safely. The plumbing is handled for you.',
    'AI features without the plumbing', 'Three servers free to start'),
  dev: nf('Dev Tool',
    'Deploy any stdio MCP server as a hosted, audited endpoint straight from GitHub. It is the fastest path from a repo to a live AI tool.',
    'Repo to live tool in minutes', 'Full logs on every call'),
  selfhost: nf('Hosting',
    'Expose your own tools to AI agents safely over MCP, with auth and logs, and no servers to maintain. Your stuff, reachable by your assistant.',
    'No servers to babysit', 'Per-tool allow lists'),
};

export const THEMES = [
  {
    id: 'ai-tools-cheating', eyebrow: 'AI Tools',
    title: '7 AI tools that feel like cheating',
    subtitle: 'The stack that quietly saves me hours every single week.',
    hook: 'sparkle',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more tools worth your time.' },
    items: [
      { name: 'ChatGPT', tag: 'AI Chat', motif: 'chat', desc: 'Your all-purpose thinking partner for drafts, code, and half-formed ideas. Ask it to plan, rewrite, or explain in plain language.', points: ['Blank page to first draft in seconds', 'Great when you are stuck'] },
      { name: 'Perplexity', tag: 'AI Search', motif: 'search', desc: 'Answers real questions with the sources attached, so you can trust the result. It reads the web so you do not have to.', points: ['Every claim links to a source', 'Ten tabs replaced by one answer'] },
      { name: 'Whisper', tag: 'Transcription', motif: 'mic', desc: 'Drop in hours of audio and get back clean, accurate text in one command. It handles accents and messy recordings with ease.', points: ['Runs offline on your machine', 'Perfect for notes and subtitles'] },
      { name: 'Midjourney', tag: 'AI Image', motif: 'image', desc: 'Turn one line of text into striking art, mockups, and moodboards. The fastest way to see an idea before you commit.', points: ['Studio visuals, zero design skill', 'Iterate a look in minutes'] },
      { name: 'Cursor', tag: 'AI Coding', motif: 'code', desc: 'An editor that writes and refactors code beside you, with your whole project in context. It feels like pairing with a senior dev.', points: ['Edits many files from one prompt', 'Catches bugs before you run'] },
      { name: 'Gamma', tag: 'Slides', motif: 'doc', desc: 'Generates polished slide decks and docs from a prompt or a rough outline. Design and layout are done for you.', points: ['A deck in minutes, not hours', 'On-brand without a designer'] },
      NF.cheating,
    ],
  },
  {
    id: 'free-sites-illegal', eyebrow: 'Free Sites',
    title: '7 free sites that feel illegal to know',
    subtitle: 'Bookmark these before they start charging.',
    hook: 'globe',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more free tools worth knowing.' },
    items: [
      { name: 'Photopea', tag: 'Editor', motif: 'image', desc: 'A full Photoshop-style editor that runs free in your browser and opens PSD files. No install, no subscription.', points: ['Opens and edits PSDs', 'Nothing to download'] },
      { name: 'Remove.bg', tag: 'Cutouts', motif: 'magnet', desc: 'Erases the background from any photo in one click. What used to take careful masking now takes a second.', points: ['Clean cutouts instantly', 'Great for product shots'] },
      { name: 'TinyWow', tag: 'Utilities', motif: 'wand', desc: 'A huge grab-bag of free PDF, image, and file tools with no sign-up. Convert, compress, and edit almost anything.', points: ['Dozens of tools, all free', 'No account needed'] },
      { name: 'Squoosh', tag: 'Compress', motif: 'bolt', desc: 'Shrinks images to a fraction of their size while keeping them sharp. A Google project that just works.', points: ['See quality vs size live', 'Runs entirely in-browser'] },
      { name: 'Excalidraw', tag: 'Whiteboard', motif: 'pen', desc: 'Sketch diagrams and ideas with a friendly hand-drawn look. Share a live board with a link.', points: ['Diagram anything in seconds', 'No sign-up to start'] },
      { name: '12ft.io', tag: 'Reader', motif: 'doc', desc: 'Strips annoying overlays so you can just read the page. Clutter and pop-ups simply disappear.', points: ['Read without the noise', 'One paste and go'] },
      { name: 'Cron', tag: 'Calendar', motif: 'calendar', desc: 'A fast, beautiful calendar that is free for individuals. Planning your day stops feeling like a chore.', points: ['Keyboard-first and quick', 'Time-zone friendly'] },
    ],
  },
  {
    id: 'ai-tools-daily', eyebrow: 'AI Tools',
    title: "7 AI tools you'll use every single day",
    subtitle: 'The ones that actually earn a spot in your routine.',
    hook: 'robot',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more daily-driver tools.' },
    items: [
      { name: 'Claude', tag: 'Reasoning', motif: 'chat', desc: 'Thoughtful help for writing, code, and hard questions that keeps your voice. It thinks before it answers.', points: ['Strong at nuanced work', 'Handles long documents'] },
      { name: 'Raycast', tag: 'Launcher', motif: 'bolt', desc: 'Launch apps, run AI, and automate from a single hotkey. It becomes the command center for your whole machine.', points: ['Everything a keystroke away', 'Extensions for every app'] },
      { name: 'Perplexity', tag: 'Search', motif: 'search', desc: 'The fastest way to get a sourced answer instead of a page of links. Ask, verify, move on.', points: ['Cited, checkable answers', 'Reads the live web'] },
      { name: 'Grammarly', tag: 'Writing', motif: 'pen', desc: 'Quietly fixes grammar, clarity, and tone as you type in any app. It catches what you stopped seeing hours ago.', points: ['Works everywhere you write', 'Explains its fixes'] },
      { name: 'Notion', tag: 'Notes', motif: 'doc', desc: 'Docs, tasks, and databases in one flexible space that bends to your workflow. Your second brain, organized.', points: ['Notes meet databases', 'Templates for everything'] },
      { name: 'CapCut', tag: 'Video', motif: 'video', desc: 'Fast edits, auto-captions, and effects built for short-form video. It is why so many clips look the way they do.', points: ['Auto captions that sync', 'Trending templates ready'] },
      NF.daily,
    ],
  },
  {
    id: 'free-worth-more', eyebrow: 'Free Tools',
    title: '6 free tools worth more than paid ones',
    subtitle: 'Free, but they quietly beat the subscriptions.',
    hook: 'sparkle',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more free upgrades.' },
    items: [
      { name: 'DaVinci Resolve', tag: 'Video', motif: 'video', desc: 'A Hollywood-grade video editor that is genuinely free. Color, audio, and effects that rival paid suites.', points: ['Pro editing, no cost', 'Used on real films'] },
      { name: 'Obsidian', tag: 'Notes', motif: 'brain', desc: 'Local markdown notes that link into a personal knowledge graph. Your thinking stays yours, in plain files.', points: ['Own your notes as files', 'Links reveal connections'] },
      { name: 'Figma', tag: 'Design', motif: 'palette', desc: 'Design and prototype anything in the browser, free for individuals. It became the industry standard for a reason.', points: ['Prototype without code', 'Real-time collaboration'] },
      { name: 'DeepL', tag: 'Translate', motif: 'globe', desc: 'Translations that read like a native speaker wrote them. The free tier already outclasses the big names.', points: ['Natural, not robotic', 'Handles whole documents'] },
      { name: 'Bitwarden', tag: 'Passwords', motif: 'shield', desc: 'Strong, unique passwords synced across devices for free. Open source and audited, unlike many paid rivals.', points: ['Unique password per site', 'Free sync everywhere'] },
      NF.free,
    ],
  },
  {
    id: 'sites-superpowers', eyebrow: 'Websites',
    title: '7 websites that feel like superpowers',
    subtitle: 'Little-known sites that make hard things easy.',
    hook: 'bolt',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more hidden-gem sites.' },
    items: [
      { name: 'Wolfram Alpha', tag: 'Answers', motif: 'brain', desc: 'Computes answers to math, science, and data questions instead of just searching. It knows, rather than links.', points: ['Step-by-step solutions', 'Real computation, not links'] },
      { name: 'Cleanup.pictures', tag: 'Retouch', motif: 'wand', desc: 'Brush over anything in a photo and it vanishes seamlessly. Remove tourists, logos, or clutter in seconds.', points: ['Erase objects in a click', 'Free and in-browser'] },
      { name: 'Regex101', tag: 'Dev', motif: 'code', desc: 'Builds and explains regular expressions as you type. It turns a dark art into something readable.', points: ['Live match highlighting', 'Explains every token'] },
      { name: 'TLDR This', tag: 'Reading', motif: 'doc', desc: 'Summarizes long articles into the key points in seconds. Get the gist without the scroll.', points: ['Long reads in seconds', 'Keeps the main points'] },
      { name: 'Photopea', tag: 'Editor', motif: 'image', desc: 'A free browser image editor that opens PSDs and rivals paid apps. Everything, no install.', points: ['Photoshop in a tab', 'Opens PSD files'] },
      { name: 'Excalidraw', tag: 'Diagrams', motif: 'pen', desc: 'Whiteboard ideas with a clean hand-drawn style and share instantly. Perfect for explaining a concept fast.', points: ['Sketch and share by link', 'No account needed'] },
      { name: 'Have I Been Pwned', tag: 'Security', motif: 'shield', desc: 'Tells you instantly if your accounts appear in a known breach. Free, trusted, and genuinely useful.', points: ['Check any email in seconds', 'Alerts on new breaches'] },
    ],
  },
  {
    id: 'ai-save-hours', eyebrow: 'AI Tools',
    title: '6 AI tools that save you hours a week',
    subtitle: 'Give the busywork to AI and get your time back.',
    hook: 'bolt',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more time-savers.' },
    items: [
      { name: 'Fireflies', tag: 'Meetings', motif: 'mic', desc: 'Joins your calls, transcribes them, and writes the summary and action items. You never take meeting notes again.', points: ['Auto notes and action items', 'Searchable call history'] },
      { name: 'Descript', tag: 'Editing', motif: 'video', desc: 'Edit audio and video by editing the transcript, and delete filler words in a click. Editing feels like a doc.', points: ['Remove ums instantly', 'No timeline wrestling'] },
      { name: 'Superhuman', tag: 'Email', motif: 'mail', desc: 'Fly through your inbox with keyboard shortcuts and AI triage. Inbox zero at a speed that feels unfair.', points: ['Blaze through email', 'AI drafts replies'] },
      { name: 'Zapier', tag: 'Automation', motif: 'gear', desc: 'Connects your apps so tasks happen automatically with zero code. If two tools have an API, it bridges them.', points: ['Automate the repetitive', 'Thousands of integrations'] },
      { name: 'Gamma', tag: 'Slides', motif: 'doc', desc: 'Turns a prompt or outline into a finished, on-brand deck. The design work disappears.', points: ['Decks in minutes', 'No design skills needed'] },
      NF.cheating,
    ],
  },
  {
    id: 'underrated-tools', eyebrow: 'Underrated',
    title: '7 underrated tools nobody talks about',
    subtitle: 'The quiet gems that punch way above their weight.',
    hook: 'magnet',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more hidden gems.' },
    items: [
      { name: 'Raycast', tag: 'Launcher', motif: 'bolt', desc: 'A hotkey launcher that quietly runs your whole Mac: apps, scripts, AI, clipboard. Once you have it you cannot go back.', points: ['One key for everything', 'Endless extensions'] },
      { name: 'Warp', tag: 'Terminal', motif: 'terminal', desc: 'A modern terminal with blocks, autocomplete, and built-in AI. It makes the command line feel friendly.', points: ['AI in your terminal', 'Reusable command blocks'] },
      { name: 'Cron', tag: 'Calendar', motif: 'calendar', desc: 'A fast, keyboard-first calendar that respects your focus. Planning a week takes a minute.', points: ['Keyboard-first speed', 'Clean, calm design'] },
      { name: 'Readwise', tag: 'Reading', motif: 'sparkle', desc: 'Resurfaces your highlights so you actually remember what you read. Turns reading into knowledge.', points: ['Daily highlight review', 'Syncs from every reader'] },
      { name: 'Raindrop', tag: 'Bookmarks', motif: 'magnet', desc: 'Save anything visually and actually find it again later. Searchable, tagged, and beautiful.', points: ['Visual bookmarking', 'Full-text search'] },
      { name: 'Bruno', tag: 'API', motif: 'plug', desc: 'A fast API client that keeps your request collections as local git-friendly files. No cloud, no account.', points: ['Collections as files', 'No login required'] },
      NF.dev,
    ],
  },
  {
    id: 'free-ai-no-catch', eyebrow: 'Free AI',
    title: '6 free AI tools with no catch',
    subtitle: 'Genuinely free, genuinely useful.',
    hook: 'sparkle',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more free AI.' },
    items: [
      { name: 'Google AI Studio', tag: 'AI Chat', motif: 'sparkle', desc: 'Free access to powerful Gemini models with a generous limit. Chat, build, and test prompts in one place.', points: ['Capable models, free', 'Great for prototyping'] },
      { name: 'Ollama', tag: 'Local AI', motif: 'terminal', desc: 'Runs open models locally with a single command, fully offline and free. Your data never leaves your machine.', points: ['One command to run', 'Private and offline'] },
      { name: 'Whisper', tag: 'Speech', motif: 'mic', desc: 'Accurate, free transcription that runs on your own hardware. Powers half the paid tools out there.', points: ['Handles noisy audio', 'Free and local'] },
      { name: 'Perplexity', tag: 'Search', motif: 'search', desc: 'Sourced AI answers with a strong free tier. Ask anything and check the receipts.', points: ['Citations on every answer', 'No account to try'] },
      { name: 'Krea', tag: 'Image', motif: 'image', desc: 'A real-time AI canvas with a free tier that renders as you sketch. See ideas appear instantly.', points: ['Real-time generation', 'Fun and free to try'] },
      NF.free,
    ],
  },
  {
    id: 'ai-boring-work', eyebrow: 'AI Tools',
    title: '7 AI tools that do the boring work for you',
    subtitle: 'Hand off the tedious stuff and focus on what matters.',
    hook: 'gear',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more busywork-killers.' },
    items: [
      { name: 'Fireflies', tag: 'Meetings', motif: 'mic', desc: 'Records, transcribes, and summarizes every meeting with action items. Note-taking is fully handled.', points: ['Never take notes again', 'Auto action items'] },
      { name: 'Mailmeteor', tag: 'Email', motif: 'mail', desc: 'Sends personalized mass emails from a spreadsheet in a few clicks. The manual copy-paste is gone.', points: ['Mail merge made easy', 'Personalize at scale'] },
      { name: 'Bardeen', tag: 'Automation', motif: 'gear', desc: 'Automates repetitive browser tasks like scraping and data entry with AI. Set it once and forget it.', points: ['Automate the browser', 'No code required'] },
      { name: 'Rows', tag: 'Spreadsheets', motif: 'chart', desc: 'A spreadsheet with AI and live data built in, so reports fill themselves. It does the lookups for you.', points: ['AI inside your sheet', 'Live data connections'] },
      { name: 'Taskade', tag: 'Tasks', motif: 'doc', desc: 'AI agents that plan projects and knock out routine to-dos with you. Turns a vague goal into steps.', points: ['AI plans your project', 'Agents do the grunt work'] },
      { name: 'Cleanvoice', tag: 'Audio', motif: 'wand', desc: 'Automatically removes filler words, stutters, and dead air from recordings. Editing time drops to nothing.', points: ['Auto-clean recordings', 'Great for podcasts'] },
      NF.power,
    ],
  },
  {
    id: 'free-replace-paid', eyebrow: 'Free Sites',
    title: '6 free sites that replace paid apps',
    subtitle: 'Cancel the subscription — these do it for free.',
    hook: 'magnet',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more free swaps.' },
    items: [
      { name: 'Canva', tag: 'Design', motif: 'palette', desc: 'Makes on-brand graphics from templates without a designer. The free tier covers most of what people pay for.', points: ['Templates for everything', 'Resize for any platform'] },
      { name: 'Photopea', tag: 'Photo', motif: 'image', desc: 'A free browser editor that opens PSDs and does what Photoshop does. No subscription, no install.', points: ['Photoshop in a tab', 'Opens PSD files'] },
      { name: 'Google Docs', tag: 'Office', motif: 'doc', desc: 'Free, real-time documents, sheets, and slides that replace the office suite. Always synced, always shared.', points: ['Real-time collaboration', 'Nothing to install'] },
      { name: 'Cal.com', tag: 'Scheduling', motif: 'calendar', desc: 'Share one link and let people book time, no paid scheduler needed. Open source and self-hostable too.', points: ['End scheduling ping-pong', 'Free and open source'] },
      { name: 'Penpot', tag: 'UI Design', motif: 'palette', desc: 'A free, open-source design and prototyping tool that rivals the paid ones. Own your files, no lock-in.', points: ['Open-source design', 'No seat limits'] },
      { name: 'Stirling PDF', tag: 'PDF', motif: 'doc', desc: 'Merge, split, sign, and convert PDFs for free, right in your browser. Replaces pricey PDF suites.', points: ['Every PDF tool, free', 'Runs locally if you want'] },
    ],
  },
  {
    id: 'ai-for-creators', eyebrow: 'AI Tools',
    title: '7 AI tools for creators',
    subtitle: 'Shoot less, ship more, with a smaller team.',
    hook: 'video',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more creator tools.' },
    items: [
      { name: 'Runway', tag: 'Video', motif: 'video', desc: 'Generate and edit video clips from text and reference frames. A whole VFX department in a browser tab.', points: ['Text-to-video in minutes', 'Powerful in-browser editing'] },
      { name: 'ElevenLabs', tag: 'Voice', motif: 'mic', desc: 'Lifelike voiceovers and dubbing in dozens of languages. Clone a voice or pick one and start narrating.', points: ['Human-quality narration', 'Dub into any language'] },
      { name: 'Suno', tag: 'Music', motif: 'sparkle', desc: 'Full original songs from a prompt, vocals and all. Royalty-free background tracks in a minute.', points: ['Original music on demand', 'Royalty-free for videos'] },
      { name: 'CapCut', tag: 'Editing', motif: 'wand', desc: 'Fast short-form edits with auto-captions, effects, and templates. Built for the way clips go viral.', points: ['Auto captions that sync', 'Trending templates'] },
      { name: 'Opus Clip', tag: 'Repurpose', motif: 'bolt', desc: 'Turns one long video into ten short, captioned clips automatically. It finds the best moments for you.', points: ['Auto-picks viral moments', 'Reframes and captions'] },
      { name: 'Ideogram', tag: 'Image', motif: 'image', desc: 'AI images that finally get text and typography right. Thumbnails and posters come out usable.', points: ['Readable text in images', 'Great for thumbnails'] },
      { name: 'Submagic', tag: 'Captions', motif: 'chat', desc: 'Animated, on-brand captions that match your pacing in seconds. The finishing touch that lifts every clip.', points: ['Styled captions fast', 'Keyword highlights'] },
    ],
  },
  {
    id: 'free-dev-steal', eyebrow: 'Dev Tools',
    title: '6 free tools every developer should steal',
    subtitle: 'Free, fast, and quietly essential.',
    hook: 'code',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more dev tools.' },
    items: [
      { name: 'VS Code', tag: 'Editor', motif: 'code', desc: 'The free editor that runs half the world with endless extensions. Light, fast, and infinitely customizable.', points: ['Extensions for anything', 'Free forever'] },
      { name: 'Warp', tag: 'Terminal', motif: 'terminal', desc: 'A modern terminal with AI, autocomplete, and command blocks. It makes the shell genuinely pleasant.', points: ['AI in your terminal', 'Reusable blocks'] },
      { name: 'ngrok', tag: 'Tunnels', motif: 'plug', desc: 'Exposes localhost to the internet in one command. Perfect for webhooks and quick demos.', points: ['Public URL in seconds', 'Inspect traffic live'] },
      { name: 'DBeaver', tag: 'Database', motif: 'database', desc: 'A free universal database client for basically every engine. Query, browse, and edit data in one place.', points: ['Works with any database', 'Free community edition'] },
      { name: 'Bruno', tag: 'API', motif: 'globe', desc: 'A fast API client that stores collections as local, git-friendly files. No account, no cloud.', points: ['Collections as files', 'Offline and private'] },
      NF.dev,
    ],
  },
  {
    id: 'replace-a-team', eyebrow: 'Solo Stack',
    title: '7 tools that replace a whole team',
    subtitle: 'Do the work of five people, on your own.',
    hook: 'rocket',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more solo-builder tools.' },
    items: [
      { name: 'ChatGPT', tag: 'Generalist', motif: 'chat', desc: 'A tireless assistant for writing, code, research, and planning. It is the teammate who never sleeps.', points: ['Any task, any time', 'Drafts to done'] },
      { name: 'Canva', tag: 'Design', motif: 'palette', desc: 'On-brand graphics, decks, and social posts without a designer on call. Templates do the heavy lifting.', points: ['Design without a designer', 'Brand kit built in'] },
      { name: 'Gamma', tag: 'Decks', motif: 'doc', desc: 'Turns a prompt into a finished presentation or one-pager. Your pitch, designed for you.', points: ['Pitch decks in minutes', 'On-brand automatically'] },
      { name: 'ElevenLabs', tag: 'Voice', motif: 'mic', desc: 'Studio-quality voiceovers without a voice actor or a booth. Narrate videos and ads instantly.', points: ['No voice actor needed', 'Any language'] },
      { name: 'Zapier', tag: 'Ops', motif: 'gear', desc: 'Wires your tools together so operations run themselves. The invisible teammate handling the busywork.', points: ['Automate your ops', 'No code needed'] },
      { name: 'HeyGen', tag: 'Video', motif: 'video', desc: 'Turns a script into a talking avatar video in any language. Record once, localize everywhere.', points: ['Avatar videos from text', 'No camera required'] },
      NF.build,
    ],
  },
  {
    id: 'free-wish-sooner', eyebrow: 'Free Sites',
    title: "6 free websites you'll wish you knew sooner",
    subtitle: 'The ones that make you say "how did I not know this?"',
    hook: 'globe',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more must-know sites.' },
    items: [
      { name: 'Unsplash', tag: 'Photos', motif: 'image', desc: 'Millions of high-quality photos, free for commercial use. Instantly lifts any post or project.', points: ['Free for commercial use', 'Endless quality photos'] },
      { name: 'Google Fonts', tag: 'Type', motif: 'doc', desc: 'A huge library of quality typefaces, free to use anywhere. Good type is one click away.', points: ['Free, quality fonts', 'Easy to embed'] },
      { name: 'Coolors', tag: 'Color', motif: 'palette', desc: 'Generates color palettes that actually work together. Hit space until a combo clicks.', points: ['Instant palettes', 'Export anywhere'] },
      { name: 'Carrd', tag: 'Sites', motif: 'rocket', desc: 'Build a clean one-page site in minutes, free. Perfect for a link page or a simple landing.', points: ['A site in minutes', 'Free tier is plenty'] },
      { name: 'Pexels', tag: 'Video', motif: 'video', desc: 'Free stock video and photos with no attribution required. B-roll for any project.', points: ['Free stock footage', 'No attribution needed'] },
      { name: 'PDF24', tag: 'PDF', motif: 'doc', desc: 'A full set of free PDF tools that run in your browser. Convert, merge, and compress with no sign-up.', points: ['Every PDF tool, free', 'No account'] },
    ],
  },
  {
    id: 'automate-boring', eyebrow: 'Automation',
    title: '7 tools to automate your boring work',
    subtitle: 'Set it once and let software do the repeating.',
    hook: 'gear',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more automation.' },
    items: [
      { name: 'Zapier', tag: 'No-Code', motif: 'bolt', desc: 'Connects thousands of apps with zero code. If two tools have an API, it bridges them in minutes.', points: ['Huge integration library', 'Build a flow fast'] },
      { name: 'Make', tag: 'Visual', motif: 'chart', desc: 'Visual scenarios for complex, branching automations. When Zapier is too simple, this handles the rest.', points: ['Branches and loops', 'See the whole flow'] },
      { name: 'n8n', tag: 'Open Source', motif: 'gear', desc: 'Open-source workflows you can self-host with no per-task fees. Add custom code when you need it.', points: ['Self-host, no limits', 'Code when needed'] },
      { name: 'Bardeen', tag: 'Browser', motif: 'globe', desc: 'Automates browser tasks like scraping and data entry with AI. Your tedious clicks, handled.', points: ['Automate the browser', 'AI-assisted steps'] },
      { name: 'IFTTT', tag: 'Simple', motif: 'sparkle', desc: 'Simple "if this then that" automations across your apps and devices. The easy on-ramp to automating life.', points: ['Dead-simple recipes', 'Great for home and phone'] },
      { name: 'Pipedream', tag: 'Dev', motif: 'code', desc: 'Developer-friendly workflows with real code steps and thousands of integrations. Glue anything to anything.', points: ['Code plus no-code', 'Generous free tier'] },
      NF.power,
    ],
  },
  {
    id: 'ai-save-a-day', eyebrow: 'AI Tools',
    title: '6 AI tools that save you a whole day',
    subtitle: 'Compress a full day of work into an afternoon.',
    hook: 'rocket',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more big time-savers.' },
    items: [
      { name: 'NotebookLM', tag: 'Research', motif: 'brain', desc: 'Upload your sources and get grounded answers, summaries, and even an audio overview. A day of reading, condensed.', points: ['Answers from your docs', 'Auto study guides'] },
      { name: 'Gamma', tag: 'Decks', motif: 'doc', desc: 'A finished, designed presentation from a single prompt. Hours of slide-fiddling, gone.', points: ['Decks in minutes', 'No design work'] },
      { name: 'Claude Code', tag: 'Coding', motif: 'terminal', desc: 'An agent that edits, runs, and tests your repo end to end. It does the multi-step grunt work while you steer.', points: ['Whole tasks, not lines', 'Runs and fixes itself'] },
      { name: 'Fireflies', tag: 'Meetings', motif: 'mic', desc: 'Turns a day of calls into clean notes, summaries, and action items. You stay present, it takes notes.', points: ['Notes for every call', 'Searchable later'] },
      { name: 'Perplexity', tag: 'Search', motif: 'search', desc: 'Does the research legwork and hands you sourced answers. Skip the twenty-tab deep dive.', points: ['Sourced answers fast', 'Follow-ups that build'] },
      NF.build,
    ],
  },
  {
    id: 'free-dev-premium', eyebrow: 'Dev Tools',
    title: '7 free developer tools that feel premium',
    subtitle: 'Polished, powerful, and somehow still free.',
    hook: 'code',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more dev upgrades.' },
    items: [
      { name: 'Warp', tag: 'Terminal', motif: 'terminal', desc: 'A gorgeous modern terminal with AI and command blocks. It feels like a paid product but is free.', points: ['AI-assisted commands', 'Blocks you can reuse'] },
      { name: 'Zed', tag: 'Editor', motif: 'code', desc: 'A blazing-fast, collaborative code editor built for speed. Opens instantly and never lags.', points: ['Extremely fast', 'Live collaboration'] },
      { name: 'Vercel', tag: 'Hosting', motif: 'rocket', desc: 'Push to git and your app is live, with previews for every change. A premium deploy experience, free to start.', points: ['Zero-config deploys', 'Preview every PR'] },
      { name: 'Supabase', tag: 'Backend', motif: 'database', desc: 'A full Postgres backend with auth and storage in minutes, free tier included. Real database, no DevOps.', points: ['Auth and APIs built in', 'Real Postgres'] },
      { name: 'Railway', tag: 'Infra', motif: 'gear', desc: 'Deploy databases and services with a clean UI and a free starter. Infrastructure that feels effortless.', points: ['Deploy in a few clicks', 'Clean, modern UI'] },
      { name: 'Resend', tag: 'Email', motif: 'mail', desc: 'A developer-first email API with a delightful dashboard. Transactional email that just works.', points: ['Clean email API', 'Great deliverability'] },
      NF.dev,
    ],
  },
  {
    id: 'ai-real-powers', eyebrow: 'AI + Tools',
    title: '6 tools to give your AI real powers',
    subtitle: 'Turn a chatbot into something that gets things done.',
    hook: 'plug',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more agent tips.' },
    items: [
      { name: 'MCP', tag: 'Standard', motif: 'plug', desc: 'The open standard that lets AI safely use tools and data. Build a tool once and any assistant can use it.', points: ['One protocol, many apps', 'Fast-growing ecosystem'] },
      { name: 'Zapier', tag: 'Actions', motif: 'gear', desc: 'Lets your AI trigger real actions across thousands of apps. Chat becomes doing.', points: ['AI that takes action', 'Thousands of apps'] },
      { name: 'Playwright', tag: 'Browser', motif: 'globe', desc: 'Gives an agent a real browser to click, type, and read pages. It can use the web like a person.', points: ['Drive a real browser', 'Scrape and test'] },
      { name: 'Composio', tag: 'Integrations', motif: 'gear', desc: 'Connects agents to hundreds of apps with auth handled. Skip building every integration yourself.', points: ['Prebuilt app actions', 'Auth taken care of'] },
      { name: 'Pinecone', tag: 'Memory', motif: 'database', desc: 'A vector database that gives your AI long-term memory and retrieval. It recalls the right context on demand.', points: ['Semantic memory', 'Scales with your data'] },
      NF.power,
    ],
  },
  {
    id: 'learn-for-free', eyebrow: 'Learning',
    title: '7 sites to learn anything for free',
    subtitle: 'World-class education that costs nothing.',
    hook: 'brain',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more free learning.' },
    items: [
      { name: 'Khan Academy', tag: 'Basics', motif: 'chart', desc: 'Free, structured courses from math to science with practice built in. Learn at your own pace, for real.', points: ['Structured and free', 'Practice as you go'] },
      { name: 'freeCodeCamp', tag: 'Coding', motif: 'code', desc: 'Learn to code for free with hands-on projects and certifications. Thousands have landed jobs from it.', points: ['Project-based coding', 'Free certifications'] },
      { name: 'CS50', tag: 'CS', motif: 'terminal', desc: "Harvard's legendary intro to computer science, free online. Rigorous, famous, and genuinely great.", points: ['Harvard-grade CS', 'Completely free'] },
      { name: 'YouTube', tag: 'Anything', motif: 'video', desc: 'The best free lectures ever made, if you curate well. Nearly any skill has a great teacher on it.', points: ['World-class teachers', 'Playlists = a curriculum'] },
      { name: 'Brilliant', tag: 'Interactive', motif: 'sparkle', desc: 'Learn math and CS by doing, not watching, in short daily lessons. It builds real intuition.', points: ['Learn by solving', 'Bite-sized lessons'] },
      { name: 'Anki', tag: 'Memory', motif: 'calendar', desc: 'Spaced-repetition flashcards that beat forgetting. Remember far more with less time.', points: ['Remember long-term', 'Decks for any subject'] },
      { name: 'MIT OpenCourseWare', tag: 'Depth', motif: 'doc', desc: 'Full MIT course materials, lectures, and problem sets, free. University-level depth on demand.', points: ['Real MIT courses', 'Notes and problem sets'] },
    ],
  },
  {
    id: 'startups-move-fast', eyebrow: 'AI Tools',
    title: '6 AI tools startups use to move fast',
    subtitle: 'How tiny teams ship like big ones.',
    hook: 'rocket',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more startup tools.' },
    items: [
      { name: 'Cursor', tag: 'Coding', motif: 'code', desc: 'Build features fast with an AI editor that knows your codebase. Small teams ship like large ones.', points: ['Codebase-aware edits', 'Fewer bugs, faster'] },
      { name: 'v0', tag: 'UI', motif: 'palette', desc: 'Generate production-ready UI from a prompt. Go from idea to a real interface in minutes.', points: ['Prompt to UI', 'Copy-paste components'] },
      { name: 'Linear', tag: 'Planning', motif: 'bolt', desc: 'Issue tracking so fast it stays out of your way. The tool fast teams swear by.', points: ['Keyboard-first speed', 'Opinionated and clean'] },
      { name: 'Supabase', tag: 'Backend', motif: 'database', desc: 'Auth, database, and storage set up in minutes. A real backend without the DevOps.', points: ['Backend in minutes', 'Scales with you'] },
      { name: 'Resend', tag: 'Email', motif: 'mail', desc: 'A clean email API for the messages your product must send. Set up in an afternoon.', points: ['Developer-first email', 'Great deliverability'] },
      NF.build,
    ],
  },
  {
    id: 'save-you-money', eyebrow: 'Money',
    title: '7 tools that quietly save you money',
    subtitle: 'Small switches that add up fast.',
    hook: 'chart',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more money savers.' },
    items: [
      { name: 'Wise', tag: 'Transfers', motif: 'globe', desc: 'Sends money abroad at the real exchange rate with tiny fees. No hidden markup buried in the rate.', points: ['Real exchange rate', 'Low, clear fees'] },
      { name: 'Actual', tag: 'Budget', motif: 'doc', desc: 'Private, local-first budgeting that is free and open source. Envelope budgeting without a subscription.', points: ['Free and private', 'Your data stays yours'] },
      { name: 'Trainline Split', tag: 'Travel', motif: 'calendar', desc: 'Finds cheaper split tickets and fares you would never spot yourself. Same journey, lower price.', points: ['Cheaper fares found', 'Same trip, less money'] },
      { name: 'PayPal Honey', tag: 'Shopping', motif: 'magnet', desc: 'Automatically tests coupon codes at checkout so you do not overpay. Savings with one click.', points: ['Auto-applies coupons', 'Works across stores'] },
      { name: 'Plausible', tag: 'Analytics', motif: 'chart', desc: 'Simple, cheap, privacy-friendly analytics that replaces bloated paid tools. All the numbers, none of the creep.', points: ['Lightweight and cheap', 'No cookie banner'] },
      { name: 'Vercel', tag: 'Hosting', motif: 'rocket', desc: 'A generous free tier that hosts real projects at no cost. Skip the server bill while you grow.', points: ['Free tier hosts a lot', 'Scale only when needed'] },
      { name: 'Cloudflare', tag: 'Infra', motif: 'cloud', desc: 'Free CDN, DNS, and security that would cost a fortune elsewhere. Fast and protected for nothing.', points: ['Free CDN and DNS', 'Real security included'] },
    ],
  },
  {
    id: 'hidden-ai-power', eyebrow: 'AI Tools',
    title: '6 hidden AI tools power users love',
    subtitle: 'The ones the pros keep to themselves.',
    hook: 'magnet',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more pro picks.' },
    items: [
      { name: 'Cline', tag: 'Coding', motif: 'code', desc: 'An open-source AI coding agent that lives in your editor and does real tasks. Power users love the control.', points: ['Agentic edits in-editor', 'Open and hackable'] },
      { name: 'Perplexity Labs', tag: 'Research', motif: 'search', desc: 'Runs deeper multi-step research and builds mini-reports. It goes further than a normal answer.', points: ['Multi-step research', 'Report-style output'] },
      { name: 'Cursor Rules', tag: 'Config', motif: 'gear', desc: 'Teach your AI editor your conventions once and it follows them everywhere. The pro way to tame AI code.', points: ['Consistent AI output', 'Set it once'] },
      { name: 'LM Studio', tag: 'Local AI', motif: 'terminal', desc: 'Discover, download, and run open models locally with a clean GUI. Test models before you commit.', points: ['Run models locally', 'Try before you buy in'] },
      { name: 'Raycast AI', tag: 'Launcher', motif: 'bolt', desc: 'AI on a hotkey, on top of every app, with custom commands. The quiet productivity multiplier.', points: ['AI without a tab', 'Custom quick commands'] },
      NF.dev,
    ],
  },
  {
    id: 'run-your-own', eyebrow: 'Self-Host',
    title: '7 free tools to run your own stuff',
    subtitle: 'Own your data instead of renting it.',
    hook: 'cloud',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more self-hosting.' },
    items: [
      { name: 'Coolify', tag: 'Deploy', motif: 'rocket', desc: 'Deploy apps and databases on your own server with a Heroku-style UI. The easy button for self-hosting.', points: ['Push to deploy', 'Your server, your rules'] },
      { name: 'Immich', tag: 'Photos', motif: 'image', desc: 'A private, self-hosted alternative to Google Photos with auto backup. Your memories on your hardware.', points: ['Auto phone backup', 'Face and object search'] },
      { name: 'Vaultwarden', tag: 'Passwords', motif: 'shield', desc: 'Your own password manager, compatible with Bitwarden apps. Your secrets never leave home.', points: ['Self-hosted vault', 'Syncs to all devices'] },
      { name: 'Nextcloud', tag: 'Cloud', motif: 'cloud', desc: 'Your own private cloud for files, calendar, and contacts. A full Google replacement you control.', points: ['Files, calendar, contacts', 'Fully yours'] },
      { name: 'Jellyfin', tag: 'Media', motif: 'video', desc: 'A free, self-hosted media server for your movies and shows. No fees, no tracking, no limits.', points: ['Your own streaming', 'Free and open source'] },
      { name: 'Uptime Kuma', tag: 'Monitoring', motif: 'chart', desc: 'Beautiful status pages and alerts for everything you run. Know something is down before users do.', points: ['Alerts anywhere', 'Gorgeous status pages'] },
      NF.selfhost,
    ],
  },
  {
    id: 'ai-like-magic', eyebrow: 'AI Tools',
    title: '6 AI tools that feel like actual magic',
    subtitle: 'The first-try moments that make you laugh out loud.',
    hook: 'wand',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more mind-blowing tools.' },
    items: [
      { name: 'Suno', tag: 'Music', motif: 'sparkle', desc: 'A full, catchy song from one sentence, vocals included. It genuinely feels impossible the first time.', points: ['Songs from a prompt', 'Royalty-free'] },
      { name: 'Runway', tag: 'Video', motif: 'video', desc: 'Type a scene and watch it become video. Cinematic shots with no camera at all.', points: ['Text becomes video', 'No shoot needed'] },
      { name: 'Adobe Podcast', tag: 'Audio', motif: 'wand', desc: 'Makes a shaky phone recording sound studio-clean. It removes echo and noise like magic.', points: ['Studio sound, free', 'Fixes bad recordings'] },
      { name: 'HeyGen', tag: 'Avatars', motif: 'robot', desc: 'Turns a script into a lifelike talking avatar in any language. Record once, speak every language.', points: ['Talking avatar from text', 'Instant translation'] },
      { name: 'Krea', tag: 'Realtime', motif: 'image', desc: 'A canvas that renders your rough sketch into art in real time. Drawing becomes instant magic.', points: ['Real-time rendering', 'Sketch to art live'] },
      NF.power,
    ],
  },
  {
    id: 'builder-bookmarks', eyebrow: 'Websites',
    title: '7 sites every builder should bookmark',
    subtitle: 'The tabs I keep open while shipping.',
    hook: 'rocket',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more builder sites.' },
    items: [
      { name: 'Excalidraw', tag: 'Diagrams', motif: 'pen', desc: 'Sketch architecture and flows fast, then share by link. Thinking out loud, visually.', points: ['Diagram in seconds', 'Share instantly'] },
      { name: 'Regex101', tag: 'Dev', motif: 'code', desc: 'Build and understand regex with live explanations. It turns guesswork into certainty.', points: ['Live match testing', 'Explains each part'] },
      { name: 'Caniuse', tag: 'Web', motif: 'globe', desc: 'Instantly shows which browsers support a feature. No more guessing what will break.', points: ['Support at a glance', 'Ship with confidence'] },
      { name: 'JSON Crack', tag: 'Data', motif: 'chart', desc: 'Turns messy JSON into a clear visual graph. Understand an API response in seconds.', points: ['Visualize any JSON', 'Spot the shape fast'] },
      { name: 'Tabler Icons', tag: 'Assets', motif: 'sparkle', desc: 'Thousands of clean, free icons in one consistent set. Your UI looks sharp instantly.', points: ['Free, consistent icons', 'Every weight you need'] },
      { name: 'Squoosh', tag: 'Images', motif: 'bolt', desc: 'Compress images to tiny sizes without losing quality. Faster pages in one drag.', points: ['Shrink images fast', 'Quality vs size, live'] },
      NF.dev,
    ],
  },
  {
    id: 'ship-solo', eyebrow: 'Solo Stack',
    title: '6 tools to ship a product solo',
    subtitle: 'Everything you need to launch on your own.',
    hook: 'rocket',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more launch tools.' },
    items: [
      { name: 'Next.js', tag: 'Framework', motif: 'code', desc: 'A batteries-included framework for building the whole web app. It handles the plumbing so you build features.', points: ['Full-stack in one place', 'Huge ecosystem'] },
      { name: 'Supabase', tag: 'Backend', motif: 'database', desc: 'Auth, database, and storage ready in minutes. A real backend without hiring a backend dev.', points: ['Backend in minutes', 'Auth out of the box'] },
      { name: 'Vercel', tag: 'Deploy', motif: 'rocket', desc: 'Push to git and your product is live, with previews for every change. Deploys handled for you.', points: ['Zero-config deploys', 'Preview every change'] },
      { name: 'Stripe', tag: 'Payments', motif: 'bolt', desc: 'Start charging customers the same day with a few lines of code. The fastest path to revenue.', points: ['Revenue in hours', 'Subscriptions made simple'] },
      { name: 'v0', tag: 'UI', motif: 'palette', desc: 'Generate a real, production UI from a prompt. Skip the blank canvas entirely.', points: ['Prompt to interface', 'Ship a UI fast'] },
      NF.build,
    ],
  },
  {
    id: 'better-than-popular', eyebrow: 'AI Tools',
    title: '7 AI tools better than the popular ones',
    subtitle: "The picks that beat the names everyone knows.",
    hook: 'sparkle',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more upgrades.' },
    items: [
      { name: 'Claude', tag: 'Writing', motif: 'chat', desc: 'Often the better writer and reasoner for serious work, and it keeps your voice. Reach for it when quality matters.', points: ['Nuanced, careful output', 'Great with long context'] },
      { name: 'Perplexity', tag: 'Search', motif: 'search', desc: 'Beats a plain search box by giving sourced answers, not links. Faster to a trustworthy result.', points: ['Answers with sources', 'Less time digging'] },
      { name: 'Ideogram', tag: 'Image', motif: 'image', desc: 'Wins where others fail: clean, readable text inside images. Posters and thumbnails come out usable.', points: ['Legible text in art', 'Strong at layouts'] },
      { name: 'Cursor', tag: 'Coding', motif: 'code', desc: 'A sharper coding experience than plain autocomplete, with whole-codebase context. Multi-file edits that land.', points: ['Knows your codebase', 'Edits across files'] },
      { name: 'Krea', tag: 'Realtime', motif: 'wand', desc: 'More fun and interactive than static image tools, rendering as you sketch. Exploration feels alive.', points: ['Real-time canvas', 'Fast iteration'] },
      { name: 'Fathom', tag: 'Meetings', motif: 'mic', desc: 'A cleaner, free meeting notetaker that just works. Summaries and highlights without the bloat.', points: ['Free and simple', 'Instant summaries'] },
      NF.cheating,
    ],
  },
  {
    id: 'make-ai-useful', eyebrow: 'AI + Tools',
    title: '6 free tools that make AI actually useful',
    subtitle: 'Turn a clever chatbot into a real workhorse.',
    hook: 'plug',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more AI power-ups.' },
    items: [
      { name: 'Ollama', tag: 'Local AI', motif: 'terminal', desc: 'Run capable open models on your own machine for free and offline. Private AI with no bill.', points: ['Free and offline', 'One command to run'] },
      { name: 'Open WebUI', tag: 'Interface', motif: 'chat', desc: 'A polished free chat interface for your local models. It feels like a hosted product, but is yours.', points: ['Clean local chat', 'Self-hosted'] },
      { name: 'AnythingLLM', tag: 'RAG', motif: 'doc', desc: 'Point it at your documents and chat with them, free and private. Your own knowledge assistant.', points: ['Chat with your docs', 'Runs locally'] },
      { name: 'n8n', tag: 'Automation', motif: 'gear', desc: 'Wire AI into real workflows with open-source automation. It connects the model to the doing.', points: ['AI in your workflows', 'Self-hostable'] },
      { name: 'MCP', tag: 'Tools', motif: 'plug', desc: 'The open standard that lets AI safely use real tools and data. Build once, use in any app.', points: ['Standard tool access', 'Growing ecosystem'] },
      NF.power,
    ],
  },
  {
    id: 'wont-believe-free', eyebrow: 'Free Tools',
    title: "7 tools you won't believe are free",
    subtitle: 'Premium power, zero price tag.',
    hook: 'sparkle',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more free finds.' },
    items: [
      { name: 'DaVinci Resolve', tag: 'Video', motif: 'video', desc: 'A film-grade editor with color and audio suites, completely free. Used on real Hollywood movies.', points: ['Pro editing, free', 'Rivals paid suites'] },
      { name: 'Blender', tag: '3D', motif: 'wand', desc: 'Full 3D modeling, animation, and rendering, free and open source. An entire studio in one download.', points: ['Complete 3D suite', 'Free forever'] },
      { name: 'Figma', tag: 'Design', motif: 'palette', desc: 'Professional design and prototyping, free for individuals. The tool most product teams use.', points: ['Design and prototype', 'Free tier is generous'] },
      { name: 'Audacity', tag: 'Audio', motif: 'mic', desc: 'A powerful audio editor that has done it all for decades, free. Record, clean, and mix anything.', points: ['Deep audio editing', 'No subscription'] },
      { name: 'Cloudflare', tag: 'Infra', motif: 'cloud', desc: 'Enterprise-grade CDN, DNS, and security on a free plan. Speed and protection that would cost a fortune.', points: ['Free CDN and security', 'Serious performance'] },
      { name: 'Notion', tag: 'Workspace', motif: 'doc', desc: 'Docs, wikis, and databases in one workspace, free for personal use. A whole toolkit in one app.', points: ['All-in-one workspace', 'Free personal plan'] },
      NF.free,
    ],
  },
  {
    id: 'cant-work-without', eyebrow: 'AI Tools',
    title: "6 AI tools I can't work without",
    subtitle: 'The daily drivers I would fight to keep.',
    hook: 'sparkle',
    closing: { title: 'Save this\nlist', subtitle: 'Follow for more essentials.' },
    items: [
      { name: 'ChatGPT', tag: 'Chat', motif: 'chat', desc: 'The default for quick answers, drafts, and thinking out loud. It is open in a tab all day.', points: ['Fast and flexible', 'Good at almost anything'] },
      { name: 'Claude', tag: 'Writing', motif: 'pen', desc: 'My pick when the writing or reasoning has to be good. Careful, and it keeps my voice.', points: ['Best for real writing', 'Long-context strong'] },
      { name: 'Cursor', tag: 'Coding', motif: 'code', desc: 'The editor that writes and refactors alongside me. I ship features noticeably faster with it.', points: ['Codebase-aware AI', 'Multi-file edits'] },
      { name: 'Perplexity', tag: 'Search', motif: 'search', desc: 'How I research now — sourced answers instead of a pile of links. Trustworthy and quick.', points: ['Cited answers', 'Saves real time'] },
      { name: 'Raycast', tag: 'Launcher', motif: 'bolt', desc: 'AI, snippets, and automations on one hotkey. The glue that ties my whole setup together.', points: ['Everything one keypress away', 'Endless extensions'] },
      NF.daily,
    ],
  },
];

export function getTheme(id) {
  return THEMES.find((t) => t.id === id) || null;
}

export function listThemes() {
  return THEMES.map((t) => ({ id: t.id, title: t.title, items: t.items.length }));
}
